<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: online_status.proto

namespace Cfwf\Micro_service\Online_status;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.online_status.UpdateOnlineStatusRequest</code>
 */
class UpdateOnlineStatusRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *登录的用户id
     *
     * Generated from protobuf field <code>uint64 userid = 1;</code>
     */
    private $userid = 0;
    /**
     *登录者ip
     *
     * Generated from protobuf field <code>string ip = 2;</code>
     */
    private $ip = '';
    /**
     *登录设备
     *
     * Generated from protobuf field <code>.cfwf.micro_service.online_status.LOGIN_DEVICE os = 3;</code>
     */
    private $os = 0;

    public function __construct() {
        \GPBMetadata\OnlineStatus::initOnce();
        parent::__construct();
    }

    /**
     *登录的用户id
     *
     * Generated from protobuf field <code>uint64 userid = 1;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     *登录的用户id
     *
     * Generated from protobuf field <code>uint64 userid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkUint64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     *登录者ip
     *
     * Generated from protobuf field <code>string ip = 2;</code>
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     *登录者ip
     *
     * Generated from protobuf field <code>string ip = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;

        return $this;
    }

    /**
     *登录设备
     *
     * Generated from protobuf field <code>.cfwf.micro_service.online_status.LOGIN_DEVICE os = 3;</code>
     * @return int
     */
    public function getOs()
    {
        return $this->os;
    }

    /**
     *登录设备
     *
     * Generated from protobuf field <code>.cfwf.micro_service.online_status.LOGIN_DEVICE os = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOs($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\Online_status\LOGIN_DEVICE::class);
        $this->os = $var;

        return $this;
    }

}

