<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto

namespace Cfwf\Micro_service\Monitor;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.monitor.AddClientVersionDownloadCountRequest</code>
 */
class AddClientVersionDownloadCountRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *下载哪个端的  1=pc 2=android 3=ios  
     *
     * Generated from protobuf field <code>int32 os = 1;</code>
     */
    private $os = 0;
    /**
     *下载哪个版本。 可不填，默认为非限定范围的当前版本。如果是限定ip范围的坂本，需要填写版本号
     *
     * Generated from protobuf field <code>string version = 2;</code>
     */
    private $version = '';
    /**
     *下载者的ip
     *
     * Generated from protobuf field <code>string ip = 3;</code>
     */
    private $ip = '';

    public function __construct() {
        \GPBMetadata\Monitor::initOnce();
        parent::__construct();
    }

    /**
     *下载哪个端的  1=pc 2=android 3=ios  
     *
     * Generated from protobuf field <code>int32 os = 1;</code>
     * @return int
     */
    public function getOs()
    {
        return $this->os;
    }

    /**
     *下载哪个端的  1=pc 2=android 3=ios  
     *
     * Generated from protobuf field <code>int32 os = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOs($var)
    {
        GPBUtil::checkInt32($var);
        $this->os = $var;

        return $this;
    }

    /**
     *下载哪个版本。 可不填，默认为非限定范围的当前版本。如果是限定ip范围的坂本，需要填写版本号
     *
     * Generated from protobuf field <code>string version = 2;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     *下载哪个版本。 可不填，默认为非限定范围的当前版本。如果是限定ip范围的坂本，需要填写版本号
     *
     * Generated from protobuf field <code>string version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     *下载者的ip
     *
     * Generated from protobuf field <code>string ip = 3;</code>
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     *下载者的ip
     *
     * Generated from protobuf field <code>string ip = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;

        return $this;
    }

}

