<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto

namespace Cfwf\Micro_service\Monitor;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.monitor.DataBaseConnAttr</code>
 */
class DataBaseConnAttr extends \Google\Protobuf\Internal\Message
{
    /**
     *保存 rabbitmq 连接属性时，此字段保存 vhost 
     *
     * Generated from protobuf field <code>string dbname = 1;</code>
     */
    private $dbname = '';
    /**
     * Generated from protobuf field <code>string host = 2;</code>
     */
    private $host = '';
    /**
     * Generated from protobuf field <code>int32 port = 3;</code>
     */
    private $port = 0;
    /**
     * Generated from protobuf field <code>string username = 4;</code>
     */
    private $username = '';
    /**
     * Generated from protobuf field <code>string password = 5;</code>
     */
    private $password = '';
    /**
     * Generated from protobuf field <code>string slave_host = 6;</code>
     */
    private $slave_host = '';
    /**
     * Generated from protobuf field <code>int32 slave_port = 7;</code>
     */
    private $slave_port = 0;
    /**
     * Generated from protobuf field <code>string slave_username = 8;</code>
     */
    private $slave_username = '';
    /**
     * Generated from protobuf field <code>string slave_password = 9;</code>
     */
    private $slave_password = '';

    public function __construct() {
        \GPBMetadata\Monitor::initOnce();
        parent::__construct();
    }

    /**
     *保存 rabbitmq 连接属性时，此字段保存 vhost 
     *
     * Generated from protobuf field <code>string dbname = 1;</code>
     * @return string
     */
    public function getDbname()
    {
        return $this->dbname;
    }

    /**
     *保存 rabbitmq 连接属性时，此字段保存 vhost 
     *
     * Generated from protobuf field <code>string dbname = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDbname($var)
    {
        GPBUtil::checkString($var, True);
        $this->dbname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string host = 2;</code>
     * @return string
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * Generated from protobuf field <code>string host = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 port = 3;</code>
     * @return int
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * Generated from protobuf field <code>int32 port = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkInt32($var);
        $this->port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string username = 4;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 5;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string slave_host = 6;</code>
     * @return string
     */
    public function getSlaveHost()
    {
        return $this->slave_host;
    }

    /**
     * Generated from protobuf field <code>string slave_host = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSlaveHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->slave_host = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 slave_port = 7;</code>
     * @return int
     */
    public function getSlavePort()
    {
        return $this->slave_port;
    }

    /**
     * Generated from protobuf field <code>int32 slave_port = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setSlavePort($var)
    {
        GPBUtil::checkInt32($var);
        $this->slave_port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string slave_username = 8;</code>
     * @return string
     */
    public function getSlaveUsername()
    {
        return $this->slave_username;
    }

    /**
     * Generated from protobuf field <code>string slave_username = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setSlaveUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->slave_username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string slave_password = 9;</code>
     * @return string
     */
    public function getSlavePassword()
    {
        return $this->slave_password;
    }

    /**
     * Generated from protobuf field <code>string slave_password = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setSlavePassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->slave_password = $var;

        return $this;
    }

}

