<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto

namespace Cfwf\Micro_service\Monitor;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.monitor.GetCurrentClientVersionResponse</code>
 */
class GetCurrentClientVersionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.monitor.RPC_CALL_RESULT result = 1;</code>
     */
    private $result = 0;
    /**
     *1=pc 2=android 3=ios
     *
     * Generated from protobuf field <code>int32 os = 2;</code>
     */
    private $os = 0;
    /**
     *版本号
     *
     * Generated from protobuf field <code>string version = 3;</code>
     */
    private $version = '';
    /**
     *安装文件下载地址，全路径 
     *
     * Generated from protobuf field <code>string setupfile_url = 4;</code>
     */
    private $setupfile_url = '';
    /**
     *安装文件大小，单位： Byte
     *
     * Generated from protobuf field <code>int32 setupfile_size = 5;</code>
     */
    private $setupfile_size = 0;
    /**
     *升级说明
     *
     * Generated from protobuf field <code>string description = 6;</code>
     */
    private $description = '';
    /**
     *0=原版 1=教师版 2=手机版
     *
     * Generated from protobuf field <code>int32 version_type = 7;</code>
     */
    private $version_type = 0;

    public function __construct() {
        \GPBMetadata\Monitor::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.monitor.RPC_CALL_RESULT result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.monitor.RPC_CALL_RESULT result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\Monitor\RPC_CALL_RESULT::class);
        $this->result = $var;

        return $this;
    }

    /**
     *1=pc 2=android 3=ios
     *
     * Generated from protobuf field <code>int32 os = 2;</code>
     * @return int
     */
    public function getOs()
    {
        return $this->os;
    }

    /**
     *1=pc 2=android 3=ios
     *
     * Generated from protobuf field <code>int32 os = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOs($var)
    {
        GPBUtil::checkInt32($var);
        $this->os = $var;

        return $this;
    }

    /**
     *版本号
     *
     * Generated from protobuf field <code>string version = 3;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     *版本号
     *
     * Generated from protobuf field <code>string version = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     *安装文件下载地址，全路径 
     *
     * Generated from protobuf field <code>string setupfile_url = 4;</code>
     * @return string
     */
    public function getSetupfileUrl()
    {
        return $this->setupfile_url;
    }

    /**
     *安装文件下载地址，全路径 
     *
     * Generated from protobuf field <code>string setupfile_url = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSetupfileUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->setupfile_url = $var;

        return $this;
    }

    /**
     *安装文件大小，单位： Byte
     *
     * Generated from protobuf field <code>int32 setupfile_size = 5;</code>
     * @return int
     */
    public function getSetupfileSize()
    {
        return $this->setupfile_size;
    }

    /**
     *安装文件大小，单位： Byte
     *
     * Generated from protobuf field <code>int32 setupfile_size = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSetupfileSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->setupfile_size = $var;

        return $this;
    }

    /**
     *升级说明
     *
     * Generated from protobuf field <code>string description = 6;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     *升级说明
     *
     * Generated from protobuf field <code>string description = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     *0=原版 1=教师版 2=手机版
     *
     * Generated from protobuf field <code>int32 version_type = 7;</code>
     * @return int
     */
    public function getVersionType()
    {
        return $this->version_type;
    }

    /**
     *0=原版 1=教师版 2=手机版
     *
     * Generated from protobuf field <code>int32 version_type = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setVersionType($var)
    {
        GPBUtil::checkInt32($var);
        $this->version_type = $var;

        return $this;
    }

}

