<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto

namespace Cfwf\Micro_service\Monitor;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.monitor.GetUpgradeFileListRequest</code>
 */
class GetUpgradeFileListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *目前固定为1 (pc)
     *
     * Generated from protobuf field <code>int32 os = 1;</code>
     */
    private $os = 0;
    /**
     *客户端版本号
     *
     * Generated from protobuf field <code>string local_version = 2;</code>
     */
    private $local_version = '';

    public function __construct() {
        \GPBMetadata\Monitor::initOnce();
        parent::__construct();
    }

    /**
     *目前固定为1 (pc)
     *
     * Generated from protobuf field <code>int32 os = 1;</code>
     * @return int
     */
    public function getOs()
    {
        return $this->os;
    }

    /**
     *目前固定为1 (pc)
     *
     * Generated from protobuf field <code>int32 os = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOs($var)
    {
        GPBUtil::checkInt32($var);
        $this->os = $var;

        return $this;
    }

    /**
     *客户端版本号
     *
     * Generated from protobuf field <code>string local_version = 2;</code>
     * @return string
     */
    public function getLocalVersion()
    {
        return $this->local_version;
    }

    /**
     *客户端版本号
     *
     * Generated from protobuf field <code>string local_version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLocalVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->local_version = $var;

        return $this;
    }

}

