<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto

namespace Cfwf\Micro_service\Monitor;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.monitor.GetUpgradeFileListRequest</code>
 */
class GetUpgradeFileListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *目前固定为1 (pc)
     *
     * Generated from protobuf field <code>int32 os = 1;</code>
     */
    private $os = 0;
    /**
     *客户端版本号
     *
     * Generated from protobuf field <code>string client_version = 2;</code>
     */
    private $client_version = '';
    /**
     *客户端ip
     *
     * Generated from protobuf field <code>string client_ip = 3;</code>
     */
    private $client_ip = '';
    /**
     *0=原版 1=教师版 2=手机版
     *
     * Generated from protobuf field <code>int32 version_type = 4;</code>
     */
    private $version_type = 0;

    public function __construct() {
        \GPBMetadata\Monitor::initOnce();
        parent::__construct();
    }

    /**
     *目前固定为1 (pc)
     *
     * Generated from protobuf field <code>int32 os = 1;</code>
     * @return int
     */
    public function getOs()
    {
        return $this->os;
    }

    /**
     *目前固定为1 (pc)
     *
     * Generated from protobuf field <code>int32 os = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOs($var)
    {
        GPBUtil::checkInt32($var);
        $this->os = $var;

        return $this;
    }

    /**
     *客户端版本号
     *
     * Generated from protobuf field <code>string client_version = 2;</code>
     * @return string
     */
    public function getClientVersion()
    {
        return $this->client_version;
    }

    /**
     *客户端版本号
     *
     * Generated from protobuf field <code>string client_version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClientVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_version = $var;

        return $this;
    }

    /**
     *客户端ip
     *
     * Generated from protobuf field <code>string client_ip = 3;</code>
     * @return string
     */
    public function getClientIp()
    {
        return $this->client_ip;
    }

    /**
     *客户端ip
     *
     * Generated from protobuf field <code>string client_ip = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setClientIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_ip = $var;

        return $this;
    }

    /**
     *0=原版 1=教师版 2=手机版
     *
     * Generated from protobuf field <code>int32 version_type = 4;</code>
     * @return int
     */
    public function getVersionType()
    {
        return $this->version_type;
    }

    /**
     *0=原版 1=教师版 2=手机版
     *
     * Generated from protobuf field <code>int32 version_type = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setVersionType($var)
    {
        GPBUtil::checkInt32($var);
        $this->version_type = $var;

        return $this;
    }

}

