<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto

namespace Cfwf\Micro_service\Monitor;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.monitor.VersionUpgradeFiles</code>
 */
class VersionUpgradeFiles extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string version = 1;</code>
     */
    private $version = '';
    /**
     *升级文件(PC静默安装) 列表
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.monitor.UpgradeFileInfo update_files = 2;</code>
     */
    private $update_files;

    public function __construct() {
        \GPBMetadata\Monitor::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string version = 1;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     *升级文件(PC静默安装) 列表
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.monitor.UpgradeFileInfo update_files = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUpdateFiles()
    {
        return $this->update_files;
    }

    /**
     *升级文件(PC静默安装) 列表
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.monitor.UpgradeFileInfo update_files = 2;</code>
     * @param \Cfwf\Micro_service\Monitor\UpgradeFileInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUpdateFiles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cfwf\Micro_service\Monitor\UpgradeFileInfo::class);
        $this->update_files = $arr;

        return $this;
    }

}

