<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yunpan.proto

namespace Cfwf\Micro_service\Yunpan;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#47;////////////////////
 *
 * Generated from protobuf message <code>cfwf.micro_service.yunpan.ResFileInfo</code>
 */
class ResFileInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 file_resid = 1;</code>
     */
    private $file_resid = 0;
    /**
     * Generated from protobuf field <code>string fastdfs_id = 2;</code>
     */
    private $fastdfs_id = '';
    /**
     * Generated from protobuf field <code>int32 res_type = 3;</code>
     */
    private $res_type = 0;
    /**
     * Generated from protobuf field <code>int64 file_size = 4;</code>
     */
    private $file_size = 0;
    /**
     * Generated from protobuf field <code>string file_name = 5;</code>
     */
    private $file_name = '';
    /**
     * Generated from protobuf field <code>bool is_pic_file = 6;</code>
     */
    private $is_pic_file = false;
    /**
     * Generated from protobuf field <code>string download_url = 7;</code>
     */
    private $download_url = '';

    public function __construct() {
        \GPBMetadata\Yunpan::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 file_resid = 1;</code>
     * @return int|string
     */
    public function getFileResid()
    {
        return $this->file_resid;
    }

    /**
     * Generated from protobuf field <code>int64 file_resid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFileResid($var)
    {
        GPBUtil::checkInt64($var);
        $this->file_resid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fastdfs_id = 2;</code>
     * @return string
     */
    public function getFastdfsId()
    {
        return $this->fastdfs_id;
    }

    /**
     * Generated from protobuf field <code>string fastdfs_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFastdfsId($var)
    {
        GPBUtil::checkString($var, True);
        $this->fastdfs_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 res_type = 3;</code>
     * @return int
     */
    public function getResType()
    {
        return $this->res_type;
    }

    /**
     * Generated from protobuf field <code>int32 res_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setResType($var)
    {
        GPBUtil::checkInt32($var);
        $this->res_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 file_size = 4;</code>
     * @return int|string
     */
    public function getFileSize()
    {
        return $this->file_size;
    }

    /**
     * Generated from protobuf field <code>int64 file_size = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFileSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->file_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string file_name = 5;</code>
     * @return string
     */
    public function getFileName()
    {
        return $this->file_name;
    }

    /**
     * Generated from protobuf field <code>string file_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFileName($var)
    {
        GPBUtil::checkString($var, True);
        $this->file_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_pic_file = 6;</code>
     * @return bool
     */
    public function getIsPicFile()
    {
        return $this->is_pic_file;
    }

    /**
     * Generated from protobuf field <code>bool is_pic_file = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsPicFile($var)
    {
        GPBUtil::checkBool($var);
        $this->is_pic_file = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string download_url = 7;</code>
     * @return string
     */
    public function getDownloadUrl()
    {
        return $this->download_url;
    }

    /**
     * Generated from protobuf field <code>string download_url = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDownloadUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->download_url = $var;

        return $this;
    }

}

