<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yunpan.proto

namespace Cfwf\Micro_service\Yunpan;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *函数： GetUploadingFileList 的 传入参数
 *
 * Generated from protobuf message <code>cfwf.micro_service.yunpan.SearchFileWhenBeginUploadRequest</code>
 */
class SearchFileWhenBeginUploadRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed64 filesize = 1;</code>
     */
    private $filesize = 0;
    /**
     * Generated from protobuf field <code>string md5 = 2;</code>
     */
    private $md5 = '';
    /**
     * Generated from protobuf field <code>string crc = 3;</code>
     */
    private $crc = '';
    /**
     * Generated from protobuf field <code>string file_ext = 4;</code>
     */
    private $file_ext = '';
    /**
     * Generated from protobuf field <code>int32 file_res_type = 5;</code>
     */
    private $file_res_type = 0;

    public function __construct() {
        \GPBMetadata\Yunpan::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>fixed64 filesize = 1;</code>
     * @return int|string
     */
    public function getFilesize()
    {
        return $this->filesize;
    }

    /**
     * Generated from protobuf field <code>fixed64 filesize = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFilesize($var)
    {
        GPBUtil::checkUint64($var);
        $this->filesize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string md5 = 2;</code>
     * @return string
     */
    public function getMd5()
    {
        return $this->md5;
    }

    /**
     * Generated from protobuf field <code>string md5 = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMd5($var)
    {
        GPBUtil::checkString($var, True);
        $this->md5 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string crc = 3;</code>
     * @return string
     */
    public function getCrc()
    {
        return $this->crc;
    }

    /**
     * Generated from protobuf field <code>string crc = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCrc($var)
    {
        GPBUtil::checkString($var, True);
        $this->crc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string file_ext = 4;</code>
     * @return string
     */
    public function getFileExt()
    {
        return $this->file_ext;
    }

    /**
     * Generated from protobuf field <code>string file_ext = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFileExt($var)
    {
        GPBUtil::checkString($var, True);
        $this->file_ext = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 file_res_type = 5;</code>
     * @return int
     */
    public function getFileResType()
    {
        return $this->file_res_type;
    }

    /**
     * Generated from protobuf field <code>int32 file_res_type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setFileResType($var)
    {
        GPBUtil::checkInt32($var);
        $this->file_res_type = $var;

        return $this;
    }

}

