<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yunpan.proto

namespace Cfwf\Micro_service\Yunpan;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *函数： SetFileBeloneTo 的 传入参数
 *
 * Generated from protobuf message <code>cfwf.micro_service.yunpan.SetFileUploadedAndBeloneToRequest</code>
 */
class SetFileUploadedAndBeloneToRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.yunpan.FileInfo fileinfo = 1;</code>
     */
    private $fileinfo = null;
    /**
     * Generated from protobuf field <code>int32 belong_type = 2;</code>
     */
    private $belong_type = 0;
    /**
     * Generated from protobuf field <code>fixed64 belong_to = 3;</code>
     */
    private $belong_to = 0;

    public function __construct() {
        \GPBMetadata\Yunpan::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.yunpan.FileInfo fileinfo = 1;</code>
     * @return \Cfwf\Micro_service\Yunpan\FileInfo
     */
    public function getFileinfo()
    {
        return $this->fileinfo;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.yunpan.FileInfo fileinfo = 1;</code>
     * @param \Cfwf\Micro_service\Yunpan\FileInfo $var
     * @return $this
     */
    public function setFileinfo($var)
    {
        GPBUtil::checkMessage($var, \Cfwf\Micro_service\Yunpan\FileInfo::class);
        $this->fileinfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 belong_type = 2;</code>
     * @return int
     */
    public function getBelongType()
    {
        return $this->belong_type;
    }

    /**
     * Generated from protobuf field <code>int32 belong_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setBelongType($var)
    {
        GPBUtil::checkInt32($var);
        $this->belong_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed64 belong_to = 3;</code>
     * @return int|string
     */
    public function getBelongTo()
    {
        return $this->belong_to;
    }

    /**
     * Generated from protobuf field <code>fixed64 belong_to = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBelongTo($var)
    {
        GPBUtil::checkUint64($var);
        $this->belong_to = $var;

        return $this;
    }

}

