<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_student.proto

namespace Cfwf\Micro_service\School_student;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *批量处理学生申请条目：用于 BatchApproveStudentApply 和 BatchRejectStudentApply
 *
 * Generated from protobuf message <code>cfwf.micro_service.school_student.BatchApproveStudentApplyRequest</code>
 */
class BatchApproveStudentApplyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed64 operatorid = 1;</code>
     */
    private $operatorid = 0;
    /**
     *申请条目列表
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.school_student.SchoolStudentApproveItem list = 2;</code>
     */
    private $list;

    public function __construct() {
        \GPBMetadata\SchoolStudent::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>fixed64 operatorid = 1;</code>
     * @return int|string
     */
    public function getOperatorid()
    {
        return $this->operatorid;
    }

    /**
     * Generated from protobuf field <code>fixed64 operatorid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOperatorid($var)
    {
        GPBUtil::checkUint64($var);
        $this->operatorid = $var;

        return $this;
    }

    /**
     *申请条目列表
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.school_student.SchoolStudentApproveItem list = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getList()
    {
        return $this->list;
    }

    /**
     *申请条目列表
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.school_student.SchoolStudentApproveItem list = 2;</code>
     * @param \Cfwf\Micro_service\School_student\SchoolStudentApproveItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cfwf\Micro_service\School_student\SchoolStudentApproveItem::class);
        $this->list = $arr;

        return $this;
    }

}

