<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_student.proto

namespace Cfwf\Micro_service\School_student;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *StudentInfo：学生信息。
 *
 * Generated from protobuf message <code>cfwf.micro_service.school_student.StudentInfo</code>
 */
class StudentInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed64 userid = 1;</code>
     */
    private $userid = 0;
    /**
     *学校id
     *
     * Generated from protobuf field <code>fixed64 schoolid = 2;</code>
     */
    private $schoolid = 0;
    /**
     *班级id
     *
     * Generated from protobuf field <code>fixed64 classid = 3;</code>
     */
    private $classid = 0;
    /**
     *0=不限制
     *
     * Generated from protobuf field <code>int32 period = 4;</code>
     */
    private $period = 0;
    /**
     *学届
     *
     * Generated from protobuf field <code>int32 grade_year = 5;</code>
     */
    private $grade_year = 0;
    /**
     *年级
     *
     * Generated from protobuf field <code>int32 grade = 6;</code>
     */
    private $grade = 0;
    /**
     *班级序号
     *
     * Generated from protobuf field <code>int32 class_no = 7;</code>
     */
    private $class_no = 0;
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.school_student.StudentInfo.STUDENT_STATUS status = 8;</code>
     */
    private $status = 0;

    public function __construct() {
        \GPBMetadata\SchoolStudent::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>fixed64 userid = 1;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     * Generated from protobuf field <code>fixed64 userid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkUint64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     *学校id
     *
     * Generated from protobuf field <code>fixed64 schoolid = 2;</code>
     * @return int|string
     */
    public function getSchoolid()
    {
        return $this->schoolid;
    }

    /**
     *学校id
     *
     * Generated from protobuf field <code>fixed64 schoolid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSchoolid($var)
    {
        GPBUtil::checkUint64($var);
        $this->schoolid = $var;

        return $this;
    }

    /**
     *班级id
     *
     * Generated from protobuf field <code>fixed64 classid = 3;</code>
     * @return int|string
     */
    public function getClassid()
    {
        return $this->classid;
    }

    /**
     *班级id
     *
     * Generated from protobuf field <code>fixed64 classid = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClassid($var)
    {
        GPBUtil::checkUint64($var);
        $this->classid = $var;

        return $this;
    }

    /**
     *0=不限制
     *
     * Generated from protobuf field <code>int32 period = 4;</code>
     * @return int
     */
    public function getPeriod()
    {
        return $this->period;
    }

    /**
     *0=不限制
     *
     * Generated from protobuf field <code>int32 period = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPeriod($var)
    {
        GPBUtil::checkInt32($var);
        $this->period = $var;

        return $this;
    }

    /**
     *学届
     *
     * Generated from protobuf field <code>int32 grade_year = 5;</code>
     * @return int
     */
    public function getGradeYear()
    {
        return $this->grade_year;
    }

    /**
     *学届
     *
     * Generated from protobuf field <code>int32 grade_year = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setGradeYear($var)
    {
        GPBUtil::checkInt32($var);
        $this->grade_year = $var;

        return $this;
    }

    /**
     *年级
     *
     * Generated from protobuf field <code>int32 grade = 6;</code>
     * @return int
     */
    public function getGrade()
    {
        return $this->grade;
    }

    /**
     *年级
     *
     * Generated from protobuf field <code>int32 grade = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setGrade($var)
    {
        GPBUtil::checkInt32($var);
        $this->grade = $var;

        return $this;
    }

    /**
     *班级序号
     *
     * Generated from protobuf field <code>int32 class_no = 7;</code>
     * @return int
     */
    public function getClassNo()
    {
        return $this->class_no;
    }

    /**
     *班级序号
     *
     * Generated from protobuf field <code>int32 class_no = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setClassNo($var)
    {
        GPBUtil::checkInt32($var);
        $this->class_no = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.school_student.StudentInfo.STUDENT_STATUS status = 8;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.school_student.StudentInfo.STUDENT_STATUS status = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\School_student\StudentInfo_STUDENT_STATUS::class);
        $this->status = $var;

        return $this;
    }

}

