<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_student.proto

namespace Cfwf\Micro_service\School_student;

/**
 * Protobuf enum <code>Cfwf\Micro_service\School_student\USER_SEX</code>
 */
class USER_SEX
{
    /**
     * Generated from protobuf enum <code>USER_SEX_GIRL = 0;</code>
     */
    const USER_SEX_GIRL = 0;
    /**
     * Generated from protobuf enum <code>USER_SEX_BOY = 1;</code>
     */
    const USER_SEX_BOY = 1;
}

