<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im_group.proto

namespace Cfwf\Micro_service\Im_group;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *发布特定群组消息，只有一个消息数目，没有文字内容
 *
 * Generated from protobuf message <code>cfwf.micro_service.im_group.BroadcastCounterMsgRequest</code>
 */
class BroadcastCounterMsgRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *信息发布者id
     *
     * Generated from protobuf field <code>int64 from_userid = 1;</code>
     */
    private $from_userid = 0;
    /**
     *接收信息的groupid
     *
     * Generated from protobuf field <code>int64 send_to_groupid = 2;</code>
     */
    private $send_to_groupid = 0;
    /**
     *classid不知道时，使用targetid 和 send_to_target_type 确定groupid 如果有必要还需加上send_to_target_unit
     *
     * Generated from protobuf field <code>int64 send_to_targetid = 3;</code>
     */
    private $send_to_targetid = 0;
    /**
     *群组所属单位
     *
     * Generated from protobuf field <code>int64 send_to_target_unit = 4;</code>
     */
    private $send_to_target_unit = 0;
    /**
     *群组类型
     *
     * Generated from protobuf field <code>.cfwf.micro_service.im_group.GROUP_TYPE send_to_target_type = 5;</code>
     */
    private $send_to_target_type = 0;
    /**
     *消息内容
     *
     * Generated from protobuf field <code>string content = 6;</code>
     */
    private $content = '';
    /**
     *消息类型 cfwf.message.CounterMessage.MESSAGE_TYPE
     *
     * Generated from protobuf field <code>int32 msg_type = 7;</code>
     */
    private $msg_type = 0;

    public function __construct() {
        \GPBMetadata\ImGroup::initOnce();
        parent::__construct();
    }

    /**
     *信息发布者id
     *
     * Generated from protobuf field <code>int64 from_userid = 1;</code>
     * @return int|string
     */
    public function getFromUserid()
    {
        return $this->from_userid;
    }

    /**
     *信息发布者id
     *
     * Generated from protobuf field <code>int64 from_userid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFromUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->from_userid = $var;

        return $this;
    }

    /**
     *接收信息的groupid
     *
     * Generated from protobuf field <code>int64 send_to_groupid = 2;</code>
     * @return int|string
     */
    public function getSendToGroupid()
    {
        return $this->send_to_groupid;
    }

    /**
     *接收信息的groupid
     *
     * Generated from protobuf field <code>int64 send_to_groupid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSendToGroupid($var)
    {
        GPBUtil::checkInt64($var);
        $this->send_to_groupid = $var;

        return $this;
    }

    /**
     *classid不知道时，使用targetid 和 send_to_target_type 确定groupid 如果有必要还需加上send_to_target_unit
     *
     * Generated from protobuf field <code>int64 send_to_targetid = 3;</code>
     * @return int|string
     */
    public function getSendToTargetid()
    {
        return $this->send_to_targetid;
    }

    /**
     *classid不知道时，使用targetid 和 send_to_target_type 确定groupid 如果有必要还需加上send_to_target_unit
     *
     * Generated from protobuf field <code>int64 send_to_targetid = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSendToTargetid($var)
    {
        GPBUtil::checkInt64($var);
        $this->send_to_targetid = $var;

        return $this;
    }

    /**
     *群组所属单位
     *
     * Generated from protobuf field <code>int64 send_to_target_unit = 4;</code>
     * @return int|string
     */
    public function getSendToTargetUnit()
    {
        return $this->send_to_target_unit;
    }

    /**
     *群组所属单位
     *
     * Generated from protobuf field <code>int64 send_to_target_unit = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSendToTargetUnit($var)
    {
        GPBUtil::checkInt64($var);
        $this->send_to_target_unit = $var;

        return $this;
    }

    /**
     *群组类型
     *
     * Generated from protobuf field <code>.cfwf.micro_service.im_group.GROUP_TYPE send_to_target_type = 5;</code>
     * @return int
     */
    public function getSendToTargetType()
    {
        return $this->send_to_target_type;
    }

    /**
     *群组类型
     *
     * Generated from protobuf field <code>.cfwf.micro_service.im_group.GROUP_TYPE send_to_target_type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSendToTargetType($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\Im_group\GROUP_TYPE::class);
        $this->send_to_target_type = $var;

        return $this;
    }

    /**
     *消息内容
     *
     * Generated from protobuf field <code>string content = 6;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     *消息内容
     *
     * Generated from protobuf field <code>string content = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     *消息类型 cfwf.message.CounterMessage.MESSAGE_TYPE
     *
     * Generated from protobuf field <code>int32 msg_type = 7;</code>
     * @return int
     */
    public function getMsgType()
    {
        return $this->msg_type;
    }

    /**
     *消息类型 cfwf.message.CounterMessage.MESSAGE_TYPE
     *
     * Generated from protobuf field <code>int32 msg_type = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setMsgType($var)
    {
        GPBUtil::checkInt32($var);
        $this->msg_type = $var;

        return $this;
    }

}

