<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im_group.proto

namespace Cfwf\Micro_service\Im_group;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.im_group.DealGroupApplyRequest</code>
 */
class DealGroupApplyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *处理者ID
     *
     * Generated from protobuf field <code>int64 operatorid = 1;</code>
     */
    private $operatorid = 0;
    /**
     *群申请的消息id
     *
     * Generated from protobuf field <code>int64 msgid = 2;</code>
     */
    private $msgid = 0;
    /**
     *群id
     *
     * Generated from protobuf field <code>int64 groupid = 3;</code>
     */
    private $groupid = 0;
    /**
     *处理结果
     *
     * Generated from protobuf field <code>.cfwf.micro_service.im_group.DEAL_GROUP_APPLY result = 4;</code>
     */
    private $result = 0;

    public function __construct() {
        \GPBMetadata\ImGroup::initOnce();
        parent::__construct();
    }

    /**
     *处理者ID
     *
     * Generated from protobuf field <code>int64 operatorid = 1;</code>
     * @return int|string
     */
    public function getOperatorid()
    {
        return $this->operatorid;
    }

    /**
     *处理者ID
     *
     * Generated from protobuf field <code>int64 operatorid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOperatorid($var)
    {
        GPBUtil::checkInt64($var);
        $this->operatorid = $var;

        return $this;
    }

    /**
     *群申请的消息id
     *
     * Generated from protobuf field <code>int64 msgid = 2;</code>
     * @return int|string
     */
    public function getMsgid()
    {
        return $this->msgid;
    }

    /**
     *群申请的消息id
     *
     * Generated from protobuf field <code>int64 msgid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgid($var)
    {
        GPBUtil::checkInt64($var);
        $this->msgid = $var;

        return $this;
    }

    /**
     *群id
     *
     * Generated from protobuf field <code>int64 groupid = 3;</code>
     * @return int|string
     */
    public function getGroupid()
    {
        return $this->groupid;
    }

    /**
     *群id
     *
     * Generated from protobuf field <code>int64 groupid = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGroupid($var)
    {
        GPBUtil::checkInt64($var);
        $this->groupid = $var;

        return $this;
    }

    /**
     *处理结果
     *
     * Generated from protobuf field <code>.cfwf.micro_service.im_group.DEAL_GROUP_APPLY result = 4;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     *处理结果
     *
     * Generated from protobuf field <code>.cfwf.micro_service.im_group.DEAL_GROUP_APPLY result = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\Im_group\DEAL_GROUP_APPLY::class);
        $this->result = $var;

        return $this;
    }

}

