<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im_group.proto

namespace Cfwf\Micro_service\Im_group;

use Google\Protobuf\Internal\GPBUtil;

/**
 *获取群列表
 *
 * Generated from protobuf message <code>cfwf.micro_service.im_group.GetGroupListRequest</code>
 */
class GetGroupListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *调用者id
     *
     * Generated from protobuf field <code>int64 userid = 1;</code>
     */
    private $userid = 0;
    /**
     *可以限定获取的群的类型。不设置表示不限制
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.im_group.GROUP_TYPE limit_group_type = 2;</code>
     */
    private $limit_group_type;

    public function __construct() {
        \GPBMetadata\ImGroup::initOnce();
        parent::__construct();
    }

    /**
     *调用者id
     *
     * Generated from protobuf field <code>int64 userid = 1;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     *调用者id
     *
     * Generated from protobuf field <code>int64 userid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     *可以限定获取的群的类型。不设置表示不限制
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.im_group.GROUP_TYPE limit_group_type = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLimitGroupType()
    {
        return $this->limit_group_type;
    }

    /**
     *可以限定获取的群的类型。不设置表示不限制
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.im_group.GROUP_TYPE limit_group_type = 2;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLimitGroupType($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Cfwf\Micro_service\Im_group\GROUP_TYPE::class);
        $this->limit_group_type = $arr;

        return $this;
    }

}

