<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im_group.proto

namespace Cfwf\Micro_service\Im_group;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.im_group.GroupApplyItem</code>
 */
class GroupApplyItem extends \Google\Protobuf\Internal\Message
{
    /**
     *申请者id
     *
     * Generated from protobuf field <code>int64 apply_userid = 1;</code>
     */
    private $apply_userid = 0;
    /**
     *申请消息id
     *
     * Generated from protobuf field <code>int64 msgid = 2;</code>
     */
    private $msgid = 0;
    /**
     *群id
     *
     * Generated from protobuf field <code>int64 groupid = 3;</code>
     */
    private $groupid = 0;
    /**
     *申请携带的内容
     *
     * Generated from protobuf field <code>string content = 4;</code>
     */
    private $content = '';
    /**
     *申请时间
     *
     * Generated from protobuf field <code>string time = 5;</code>
     */
    private $time = '';

    public function __construct() {
        \GPBMetadata\ImGroup::initOnce();
        parent::__construct();
    }

    /**
     *申请者id
     *
     * Generated from protobuf field <code>int64 apply_userid = 1;</code>
     * @return int|string
     */
    public function getApplyUserid()
    {
        return $this->apply_userid;
    }

    /**
     *申请者id
     *
     * Generated from protobuf field <code>int64 apply_userid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setApplyUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->apply_userid = $var;

        return $this;
    }

    /**
     *申请消息id
     *
     * Generated from protobuf field <code>int64 msgid = 2;</code>
     * @return int|string
     */
    public function getMsgid()
    {
        return $this->msgid;
    }

    /**
     *申请消息id
     *
     * Generated from protobuf field <code>int64 msgid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgid($var)
    {
        GPBUtil::checkInt64($var);
        $this->msgid = $var;

        return $this;
    }

    /**
     *群id
     *
     * Generated from protobuf field <code>int64 groupid = 3;</code>
     * @return int|string
     */
    public function getGroupid()
    {
        return $this->groupid;
    }

    /**
     *群id
     *
     * Generated from protobuf field <code>int64 groupid = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGroupid($var)
    {
        GPBUtil::checkInt64($var);
        $this->groupid = $var;

        return $this;
    }

    /**
     *申请携带的内容
     *
     * Generated from protobuf field <code>string content = 4;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     *申请携带的内容
     *
     * Generated from protobuf field <code>string content = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     *申请时间
     *
     * Generated from protobuf field <code>string time = 5;</code>
     * @return string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     *申请时间
     *
     * Generated from protobuf field <code>string time = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->time = $var;

        return $this;
    }

}

