<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im_group.proto

namespace Cfwf\Micro_service\Im_group;

/**
 *发送群聊天
 *
 * Protobuf enum <code>Cfwf\Micro_service\Im_group\IM_GROUP_SPEACK_TYPE</code>
 */
class IM_GROUP_SPEACK_TYPE
{
    /**
     * Generated from protobuf enum <code>IM_GROUP_SPEACK_TYPE_INIT = 0;</code>
     */
    const IM_GROUP_SPEACK_TYPE_INIT = 0;
    /**
     *图文混排
     *
     * Generated from protobuf enum <code>IM_GROUP_SPEACK_MIX = 1;</code>
     */
    const IM_GROUP_SPEACK_MIX = 1;
    /**
     *文件  
     *
     * Generated from protobuf enum <code>IM_GROUP_SPEACK_FILE = 2;</code>
     */
    const IM_GROUP_SPEACK_FILE = 2;
    /**
     *图片
     *
     * Generated from protobuf enum <code>IM_GROUP_SPEACK_IMAGE = 3;</code>
     */
    const IM_GROUP_SPEACK_IMAGE = 3;
    /**
     *语音
     *
     * Generated from protobuf enum <code>IM_GROUP_SPEACK_AUDIO = 4;</code>
     */
    const IM_GROUP_SPEACK_AUDIO = 4;
    /**
     *超链接
     *
     * Generated from protobuf enum <code>IM_GROUP_SPEACK_LINK = 5;</code>
     */
    const IM_GROUP_SPEACK_LINK = 5;
    /**
     *撤销某条消息
     *
     * Generated from protobuf enum <code>IM_GROUP_SPEACK_UNDO = 6;</code>
     */
    const IM_GROUP_SPEACK_UNDO = 6;
    /**
     *详情消息
     *
     * Generated from protobuf enum <code>IM_GROUP_SPEACK_DETAIL = 7;</code>
     */
    const IM_GROUP_SPEACK_DETAIL = 7;
    /**
     *系统通知。
     *
     * Generated from protobuf enum <code>IM_GROUP_SPEACK_SYSTEM_INFORM = 8;</code>
     */
    const IM_GROUP_SPEACK_SYSTEM_INFORM = 8;
}

