<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im_group.proto

namespace Cfwf\Micro_service\Im_group;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *发布群公告
 *
 * Generated from protobuf message <code>cfwf.micro_service.im_group.InsertGruopInformRequest</code>
 */
class InsertGruopInformRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.im_group.GruopInformItem item = 1;</code>
     */
    private $item = null;

    public function __construct() {
        \GPBMetadata\ImGroup::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.im_group.GruopInformItem item = 1;</code>
     * @return \Cfwf\Micro_service\Im_group\GruopInformItem
     */
    public function getItem()
    {
        return $this->item;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.im_group.GruopInformItem item = 1;</code>
     * @param \Cfwf\Micro_service\Im_group\GruopInformItem $var
     * @return $this
     */
    public function setItem($var)
    {
        GPBUtil::checkMessage($var, \Cfwf\Micro_service\Im_group\GruopInformItem::class);
        $this->item = $var;

        return $this;
    }

}

