<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im_group.proto

namespace Cfwf\Micro_service\Im_group;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.im_group.SetSuperAdminRespnse</code>
 */
class SetSuperAdminRespnse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.im_group.RPC_CALL_RESULT result = 1;</code>
     */
    private $result = 0;
    /**
     *返回被设置的超级管理员id
     *
     * Generated from protobuf field <code>int64 super_admin_userid = 2;</code>
     */
    private $super_admin_userid = 0;
    /**
     *返回群组id
     *
     * Generated from protobuf field <code>int64 group_id = 3;</code>
     */
    private $group_id = 0;

    public function __construct() {
        \GPBMetadata\ImGroup::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.im_group.RPC_CALL_RESULT result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.im_group.RPC_CALL_RESULT result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\Im_group\RPC_CALL_RESULT::class);
        $this->result = $var;

        return $this;
    }

    /**
     *返回被设置的超级管理员id
     *
     * Generated from protobuf field <code>int64 super_admin_userid = 2;</code>
     * @return int|string
     */
    public function getSuperAdminUserid()
    {
        return $this->super_admin_userid;
    }

    /**
     *返回被设置的超级管理员id
     *
     * Generated from protobuf field <code>int64 super_admin_userid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSuperAdminUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->super_admin_userid = $var;

        return $this;
    }

    /**
     *返回群组id
     *
     * Generated from protobuf field <code>int64 group_id = 3;</code>
     * @return int|string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     *返回群组id
     *
     * Generated from protobuf field <code>int64 group_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkInt64($var);
        $this->group_id = $var;

        return $this;
    }

}

