<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resource_statistics.proto

namespace Cfwf\Micro_service\Resource_statistics;

use Google\Protobuf\Internal\GPBUtil;

/**
 *GetResourceCount
 *
 * Generated from protobuf message <code>cfwf.micro_service.resource_statistics.GetResourceCountRequest</code>
 */
class GetResourceCountRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 0 = 获取全国统计数
     *
     * Generated from protobuf field <code>int32 cityid = 1;</code>
     */
    private $cityid = 0;

    public function __construct() {
        \GPBMetadata\ResourceStatistics::initOnce();
        parent::__construct();
    }

    /**
     * 0 = 获取全国统计数
     *
     * Generated from protobuf field <code>int32 cityid = 1;</code>
     * @return int
     */
    public function getCityid()
    {
        return $this->cityid;
    }

    /**
     * 0 = 获取全国统计数
     *
     * Generated from protobuf field <code>int32 cityid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCityid($var)
    {
        GPBUtil::checkInt32($var);
        $this->cityid = $var;

        return $this;
    }

}

