<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resource_statistics.proto

namespace Cfwf\Micro_service\Resource_statistics;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.resource_statistics.GetResourceCountResponse</code>
 */
class GetResourceCountResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.resource_statistics.RPC_CALL_RESULT result = 1;</code>
     */
    private $result = 0;
    /**
     * Generated from protobuf field <code>int32 cityid = 2;</code>
     */
    private $cityid = 0;
    /**
     *全国有云平台的省数目
     *
     * Generated from protobuf field <code>int32 yun_sheng = 3;</code>
     */
    private $yun_sheng = 0;
    /**
     *全国有云平台的市数目
     *
     * Generated from protobuf field <code>int32 yun_shi = 4;</code>
     */
    private $yun_shi = 0;
    /**
     *  cityid以及其子节点 的全部用户数 
     *
     * Generated from protobuf field <code>int64 user_count = 5;</code>
     */
    private $user_count = 0;
    /**
     *  cityid以及其子节点 的全部学校数 
     *
     * Generated from protobuf field <code>int64 school_count = 6;</code>
     */
    private $school_count = 0;
    /**
     *  cityid以及其子节点 的全部视频数 
     *
     * Generated from protobuf field <code>int64 video_count = 7;</code>
     */
    private $video_count = 0;
    /**
     *  cityid以及其子节点 的全部文章数 
     *
     * Generated from protobuf field <code>int64 article_count = 8;</code>
     */
    private $article_count = 0;

    public function __construct() {
        \GPBMetadata\ResourceStatistics::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.resource_statistics.RPC_CALL_RESULT result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.resource_statistics.RPC_CALL_RESULT result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\Resource_statistics\RPC_CALL_RESULT::class);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cityid = 2;</code>
     * @return int
     */
    public function getCityid()
    {
        return $this->cityid;
    }

    /**
     * Generated from protobuf field <code>int32 cityid = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCityid($var)
    {
        GPBUtil::checkInt32($var);
        $this->cityid = $var;

        return $this;
    }

    /**
     *全国有云平台的省数目
     *
     * Generated from protobuf field <code>int32 yun_sheng = 3;</code>
     * @return int
     */
    public function getYunSheng()
    {
        return $this->yun_sheng;
    }

    /**
     *全国有云平台的省数目
     *
     * Generated from protobuf field <code>int32 yun_sheng = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setYunSheng($var)
    {
        GPBUtil::checkInt32($var);
        $this->yun_sheng = $var;

        return $this;
    }

    /**
     *全国有云平台的市数目
     *
     * Generated from protobuf field <code>int32 yun_shi = 4;</code>
     * @return int
     */
    public function getYunShi()
    {
        return $this->yun_shi;
    }

    /**
     *全国有云平台的市数目
     *
     * Generated from protobuf field <code>int32 yun_shi = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setYunShi($var)
    {
        GPBUtil::checkInt32($var);
        $this->yun_shi = $var;

        return $this;
    }

    /**
     *  cityid以及其子节点 的全部用户数 
     *
     * Generated from protobuf field <code>int64 user_count = 5;</code>
     * @return int|string
     */
    public function getUserCount()
    {
        return $this->user_count;
    }

    /**
     *  cityid以及其子节点 的全部用户数 
     *
     * Generated from protobuf field <code>int64 user_count = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_count = $var;

        return $this;
    }

    /**
     *  cityid以及其子节点 的全部学校数 
     *
     * Generated from protobuf field <code>int64 school_count = 6;</code>
     * @return int|string
     */
    public function getSchoolCount()
    {
        return $this->school_count;
    }

    /**
     *  cityid以及其子节点 的全部学校数 
     *
     * Generated from protobuf field <code>int64 school_count = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSchoolCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->school_count = $var;

        return $this;
    }

    /**
     *  cityid以及其子节点 的全部视频数 
     *
     * Generated from protobuf field <code>int64 video_count = 7;</code>
     * @return int|string
     */
    public function getVideoCount()
    {
        return $this->video_count;
    }

    /**
     *  cityid以及其子节点 的全部视频数 
     *
     * Generated from protobuf field <code>int64 video_count = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVideoCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->video_count = $var;

        return $this;
    }

    /**
     *  cityid以及其子节点 的全部文章数 
     *
     * Generated from protobuf field <code>int64 article_count = 8;</code>
     * @return int|string
     */
    public function getArticleCount()
    {
        return $this->article_count;
    }

    /**
     *  cityid以及其子节点 的全部文章数 
     *
     * Generated from protobuf field <code>int64 article_count = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setArticleCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->article_count = $var;

        return $this;
    }

}

