<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resource_statistics.proto

namespace Cfwf\Micro_service\Resource_statistics;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *获取学校统计信息(学校->地图->学校  第一期) 
 *GetSchoolStatistics
 *
 * Generated from protobuf message <code>cfwf.micro_service.resource_statistics.GetSchoolStatisticsRequest</code>
 */
class GetSchoolStatisticsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *必须填写，不能为0。返回此city,以及下级地区 所有的学校列表
     *
     * Generated from protobuf field <code>int32 cityid = 1;</code>
     */
    private $cityid = 0;

    public function __construct() {
        \GPBMetadata\ResourceStatistics::initOnce();
        parent::__construct();
    }

    /**
     *必须填写，不能为0。返回此city,以及下级地区 所有的学校列表
     *
     * Generated from protobuf field <code>int32 cityid = 1;</code>
     * @return int
     */
    public function getCityid()
    {
        return $this->cityid;
    }

    /**
     *必须填写，不能为0。返回此city,以及下级地区 所有的学校列表
     *
     * Generated from protobuf field <code>int32 cityid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCityid($var)
    {
        GPBUtil::checkInt32($var);
        $this->cityid = $var;

        return $this;
    }

}

