<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resource_statistics.proto

namespace Cfwf\Micro_service\Resource_statistics;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.resource_statistics.GetSchoolInfoResponse</code>
 */
class GetSchoolInfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.resource_statistics.RPC_CALL_RESULT result = 1;</code>
     */
    private $result = 0;
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.resource_statistics.SchoolInfo school_info = 2;</code>
     */
    private $school_info = null;

    public function __construct() {
        \GPBMetadata\ResourceStatistics::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.resource_statistics.RPC_CALL_RESULT result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.resource_statistics.RPC_CALL_RESULT result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\Resource_statistics\RPC_CALL_RESULT::class);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.resource_statistics.SchoolInfo school_info = 2;</code>
     * @return \Cfwf\Micro_service\Resource_statistics\SchoolInfo
     */
    public function getSchoolInfo()
    {
        return $this->school_info;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.resource_statistics.SchoolInfo school_info = 2;</code>
     * @param \Cfwf\Micro_service\Resource_statistics\SchoolInfo $var
     * @return $this
     */
    public function setSchoolInfo($var)
    {
        GPBUtil::checkMessage($var, \Cfwf\Micro_service\Resource_statistics\SchoolInfo::class);
        $this->school_info = $var;

        return $this;
    }

}

