<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resource_statistics.proto

namespace Cfwf\Micro_service\Resource_statistics;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.resource_statistics.SchoolInfo</code>
 */
class SchoolInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.resource_statistics.SchoolInfoSimple simple_info = 1;</code>
     */
    private $simple_info = null;
    /**
     *地址
     *
     * Generated from protobuf field <code>string address = 2;</code>
     */
    private $address = '';
    /**
     *教室数量
     *
     * Generated from protobuf field <code>int64 classroom_count = 3;</code>
     */
    private $classroom_count = 0;
    /**
     *录播设备安装套数
     *
     * Generated from protobuf field <code>int64 lubo_install_count = 4;</code>
     */
    private $lubo_install_count = 0;
    /**
     *直播设备安装套数
     *
     * Generated from protobuf field <code>int64 zhibo_install_count = 5;</code>
     */
    private $zhibo_install_count = 0;
    /**
     *邮编
     *
     * Generated from protobuf field <code>string zip_code = 6;</code>
     */
    private $zip_code = '';
    /**
     *电话
     *
     * Generated from protobuf field <code>string tel = 7;</code>
     */
    private $tel = '';
    /**
     *传真
     *
     * Generated from protobuf field <code>string fax = 8;</code>
     */
    private $fax = '';
    /**
     *开学时间，上学期
     *
     * Generated from protobuf field <code>string first_term_start_date = 9;</code>
     */
    private $first_term_start_date = '';
    /**
     *开学时间，下学期
     *
     * Generated from protobuf field <code>string second_term_start_date = 10;</code>
     */
    private $second_term_start_date = '';
    /**
     *校长名称
     *
     * Generated from protobuf field <code>string schoolmaster_name = 11;</code>
     */
    private $schoolmaster_name = '';
    /**
     *校长性别
     *
     * Generated from protobuf field <code>.cfwf.micro_service.resource_statistics.USER_SEX schoolmaster_sex = 12;</code>
     */
    private $schoolmaster_sex = 0;
    /**
     *校长用户id
     *
     * Generated from protobuf field <code>int64 schoolmaster_userid = 13;</code>
     */
    private $schoolmaster_userid = 0;
    /**
     *校长电话
     *
     * Generated from protobuf field <code>string schoolmaster_tel = 14;</code>
     */
    private $schoolmaster_tel = '';

    public function __construct() {
        \GPBMetadata\ResourceStatistics::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.resource_statistics.SchoolInfoSimple simple_info = 1;</code>
     * @return \Cfwf\Micro_service\Resource_statistics\SchoolInfoSimple
     */
    public function getSimpleInfo()
    {
        return $this->simple_info;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.resource_statistics.SchoolInfoSimple simple_info = 1;</code>
     * @param \Cfwf\Micro_service\Resource_statistics\SchoolInfoSimple $var
     * @return $this
     */
    public function setSimpleInfo($var)
    {
        GPBUtil::checkMessage($var, \Cfwf\Micro_service\Resource_statistics\SchoolInfoSimple::class);
        $this->simple_info = $var;

        return $this;
    }

    /**
     *地址
     *
     * Generated from protobuf field <code>string address = 2;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     *地址
     *
     * Generated from protobuf field <code>string address = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     *教室数量
     *
     * Generated from protobuf field <code>int64 classroom_count = 3;</code>
     * @return int|string
     */
    public function getClassroomCount()
    {
        return $this->classroom_count;
    }

    /**
     *教室数量
     *
     * Generated from protobuf field <code>int64 classroom_count = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClassroomCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->classroom_count = $var;

        return $this;
    }

    /**
     *录播设备安装套数
     *
     * Generated from protobuf field <code>int64 lubo_install_count = 4;</code>
     * @return int|string
     */
    public function getLuboInstallCount()
    {
        return $this->lubo_install_count;
    }

    /**
     *录播设备安装套数
     *
     * Generated from protobuf field <code>int64 lubo_install_count = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLuboInstallCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->lubo_install_count = $var;

        return $this;
    }

    /**
     *直播设备安装套数
     *
     * Generated from protobuf field <code>int64 zhibo_install_count = 5;</code>
     * @return int|string
     */
    public function getZhiboInstallCount()
    {
        return $this->zhibo_install_count;
    }

    /**
     *直播设备安装套数
     *
     * Generated from protobuf field <code>int64 zhibo_install_count = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setZhiboInstallCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->zhibo_install_count = $var;

        return $this;
    }

    /**
     *邮编
     *
     * Generated from protobuf field <code>string zip_code = 6;</code>
     * @return string
     */
    public function getZipCode()
    {
        return $this->zip_code;
    }

    /**
     *邮编
     *
     * Generated from protobuf field <code>string zip_code = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setZipCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->zip_code = $var;

        return $this;
    }

    /**
     *电话
     *
     * Generated from protobuf field <code>string tel = 7;</code>
     * @return string
     */
    public function getTel()
    {
        return $this->tel;
    }

    /**
     *电话
     *
     * Generated from protobuf field <code>string tel = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTel($var)
    {
        GPBUtil::checkString($var, True);
        $this->tel = $var;

        return $this;
    }

    /**
     *传真
     *
     * Generated from protobuf field <code>string fax = 8;</code>
     * @return string
     */
    public function getFax()
    {
        return $this->fax;
    }

    /**
     *传真
     *
     * Generated from protobuf field <code>string fax = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setFax($var)
    {
        GPBUtil::checkString($var, True);
        $this->fax = $var;

        return $this;
    }

    /**
     *开学时间，上学期
     *
     * Generated from protobuf field <code>string first_term_start_date = 9;</code>
     * @return string
     */
    public function getFirstTermStartDate()
    {
        return $this->first_term_start_date;
    }

    /**
     *开学时间，上学期
     *
     * Generated from protobuf field <code>string first_term_start_date = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstTermStartDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->first_term_start_date = $var;

        return $this;
    }

    /**
     *开学时间，下学期
     *
     * Generated from protobuf field <code>string second_term_start_date = 10;</code>
     * @return string
     */
    public function getSecondTermStartDate()
    {
        return $this->second_term_start_date;
    }

    /**
     *开学时间，下学期
     *
     * Generated from protobuf field <code>string second_term_start_date = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setSecondTermStartDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->second_term_start_date = $var;

        return $this;
    }

    /**
     *校长名称
     *
     * Generated from protobuf field <code>string schoolmaster_name = 11;</code>
     * @return string
     */
    public function getSchoolmasterName()
    {
        return $this->schoolmaster_name;
    }

    /**
     *校长名称
     *
     * Generated from protobuf field <code>string schoolmaster_name = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setSchoolmasterName($var)
    {
        GPBUtil::checkString($var, True);
        $this->schoolmaster_name = $var;

        return $this;
    }

    /**
     *校长性别
     *
     * Generated from protobuf field <code>.cfwf.micro_service.resource_statistics.USER_SEX schoolmaster_sex = 12;</code>
     * @return int
     */
    public function getSchoolmasterSex()
    {
        return $this->schoolmaster_sex;
    }

    /**
     *校长性别
     *
     * Generated from protobuf field <code>.cfwf.micro_service.resource_statistics.USER_SEX schoolmaster_sex = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setSchoolmasterSex($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\Resource_statistics\USER_SEX::class);
        $this->schoolmaster_sex = $var;

        return $this;
    }

    /**
     *校长用户id
     *
     * Generated from protobuf field <code>int64 schoolmaster_userid = 13;</code>
     * @return int|string
     */
    public function getSchoolmasterUserid()
    {
        return $this->schoolmaster_userid;
    }

    /**
     *校长用户id
     *
     * Generated from protobuf field <code>int64 schoolmaster_userid = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSchoolmasterUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->schoolmaster_userid = $var;

        return $this;
    }

    /**
     *校长电话
     *
     * Generated from protobuf field <code>string schoolmaster_tel = 14;</code>
     * @return string
     */
    public function getSchoolmasterTel()
    {
        return $this->schoolmaster_tel;
    }

    /**
     *校长电话
     *
     * Generated from protobuf field <code>string schoolmaster_tel = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setSchoolmasterTel($var)
    {
        GPBUtil::checkString($var, True);
        $this->schoolmaster_tel = $var;

        return $this;
    }

}

