<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resource_statistics.proto

namespace Cfwf\Micro_service\Resource_statistics;

/**
 * Protobuf enum <code>Cfwf\Micro_service\Resource_statistics\USER_SEX</code>
 */
class USER_SEX
{
    /**
     * Generated from protobuf enum <code>USER_SEX_NONE = 0;</code>
     */
    const USER_SEX_NONE = 0;
    /**
     *女
     *
     * Generated from protobuf enum <code>USER_SEX_WOMAN = 1;</code>
     */
    const USER_SEX_WOMAN = 1;
    /**
     *男
     *
     * Generated from protobuf enum <code>USER_SEX_MAN = 2;</code>
     */
    const USER_SEX_MAN = 2;
}

