<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resource_statistics.proto

namespace Cfwf\Micro_service\Resource_statistics;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.resource_statistics.UserInfo</code>
 */
class UserInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.resource_statistics.UserInfoSimple simple_info = 1;</code>
     */
    private $simple_info = null;
    /**
     *详情内容
     *
     * Generated from protobuf field <code>string real_name = 2;</code>
     */
    private $real_name = '';
    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile_phone = 3;</code>
     */
    private $mobile_phone = '';
    /**
     *签名， 心情
     *
     * Generated from protobuf field <code>string mood = 5;</code>
     */
    private $mood = '';
    /**
     *身份证号
     *
     * Generated from protobuf field <code>string card_code = 6;</code>
     */
    private $card_code = '';
    /**
     *地区
     *
     * Generated from protobuf field <code>string address = 7;</code>
     */
    private $address = '';
    /**
     *任教信息
     *
     * Generated from protobuf field <code>string teach_info = 8;</code>
     */
    private $teach_info = '';

    public function __construct() {
        \GPBMetadata\ResourceStatistics::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.resource_statistics.UserInfoSimple simple_info = 1;</code>
     * @return \Cfwf\Micro_service\Resource_statistics\UserInfoSimple
     */
    public function getSimpleInfo()
    {
        return $this->simple_info;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.resource_statistics.UserInfoSimple simple_info = 1;</code>
     * @param \Cfwf\Micro_service\Resource_statistics\UserInfoSimple $var
     * @return $this
     */
    public function setSimpleInfo($var)
    {
        GPBUtil::checkMessage($var, \Cfwf\Micro_service\Resource_statistics\UserInfoSimple::class);
        $this->simple_info = $var;

        return $this;
    }

    /**
     *详情内容
     *
     * Generated from protobuf field <code>string real_name = 2;</code>
     * @return string
     */
    public function getRealName()
    {
        return $this->real_name;
    }

    /**
     *详情内容
     *
     * Generated from protobuf field <code>string real_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRealName($var)
    {
        GPBUtil::checkString($var, True);
        $this->real_name = $var;

        return $this;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile_phone = 3;</code>
     * @return string
     */
    public function getMobilePhone()
    {
        return $this->mobile_phone;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string mobile_phone = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMobilePhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile_phone = $var;

        return $this;
    }

    /**
     *签名， 心情
     *
     * Generated from protobuf field <code>string mood = 5;</code>
     * @return string
     */
    public function getMood()
    {
        return $this->mood;
    }

    /**
     *签名， 心情
     *
     * Generated from protobuf field <code>string mood = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMood($var)
    {
        GPBUtil::checkString($var, True);
        $this->mood = $var;

        return $this;
    }

    /**
     *身份证号
     *
     * Generated from protobuf field <code>string card_code = 6;</code>
     * @return string
     */
    public function getCardCode()
    {
        return $this->card_code;
    }

    /**
     *身份证号
     *
     * Generated from protobuf field <code>string card_code = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCardCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->card_code = $var;

        return $this;
    }

    /**
     *地区
     *
     * Generated from protobuf field <code>string address = 7;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     *地区
     *
     * Generated from protobuf field <code>string address = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     *任教信息
     *
     * Generated from protobuf field <code>string teach_info = 8;</code>
     * @return string
     */
    public function getTeachInfo()
    {
        return $this->teach_info;
    }

    /**
     *任教信息
     *
     * Generated from protobuf field <code>string teach_info = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setTeachInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->teach_info = $var;

        return $this;
    }

}

