<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_seatwork.proto

namespace Cfwf\Micro_service\School_seatwork;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_seatwork.BeginSeatWorkTestingRequest</code>
 */
class BeginSeatWorkTestingRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 userid = 1;</code>
     */
    private $userid = 0;
    /**
     * Generated from protobuf field <code>int64 seatwork_id = 2;</code>
     */
    private $seatwork_id = 0;
    /**
     * Generated from protobuf field <code>bool start_count_down = 3;</code>
     */
    private $start_count_down = false;

    public function __construct() {
        \GPBMetadata\SchoolSeatwork::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 userid = 1;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     * Generated from protobuf field <code>int64 userid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 seatwork_id = 2;</code>
     * @return int|string
     */
    public function getSeatworkId()
    {
        return $this->seatwork_id;
    }

    /**
     * Generated from protobuf field <code>int64 seatwork_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSeatworkId($var)
    {
        GPBUtil::checkInt64($var);
        $this->seatwork_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool start_count_down = 3;</code>
     * @return bool
     */
    public function getStartCountDown()
    {
        return $this->start_count_down;
    }

    /**
     * Generated from protobuf field <code>bool start_count_down = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setStartCountDown($var)
    {
        GPBUtil::checkBool($var);
        $this->start_count_down = $var;

        return $this;
    }

}

