<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_seatwork.proto

namespace Cfwf\Micro_service\School_seatwork;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_seatwork.DeleteSeatWorkRequest</code>
 */
class DeleteSeatWorkRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 userid = 1;</code>
     */
    private $userid = 0;
    /**
     *true: 只有随堂检测发布人能删除
     *
     * Generated from protobuf field <code>bool check_user = 2;</code>
     */
    private $check_user = false;
    /**
     * Generated from protobuf field <code>repeated int64 seatwork_id = 3;</code>
     */
    private $seatwork_id;

    public function __construct() {
        \GPBMetadata\SchoolSeatwork::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 userid = 1;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     * Generated from protobuf field <code>int64 userid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     *true: 只有随堂检测发布人能删除
     *
     * Generated from protobuf field <code>bool check_user = 2;</code>
     * @return bool
     */
    public function getCheckUser()
    {
        return $this->check_user;
    }

    /**
     *true: 只有随堂检测发布人能删除
     *
     * Generated from protobuf field <code>bool check_user = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setCheckUser($var)
    {
        GPBUtil::checkBool($var);
        $this->check_user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 seatwork_id = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSeatworkId()
    {
        return $this->seatwork_id;
    }

    /**
     * Generated from protobuf field <code>repeated int64 seatwork_id = 3;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSeatworkId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->seatwork_id = $arr;

        return $this;
    }

}

