<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_seatwork.proto

namespace Cfwf\Micro_service\School_seatwork;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_seatwork.MySeatWorkAnswer</code>
 */
class MySeatWorkAnswer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 question_id = 1;</code>
     */
    private $question_id = 0;
    /**
     * Generated from protobuf field <code>string myanswer = 2;</code>
     */
    private $myanswer = '';

    public function __construct() {
        \GPBMetadata\SchoolSeatwork::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 question_id = 1;</code>
     * @return int|string
     */
    public function getQuestionId()
    {
        return $this->question_id;
    }

    /**
     * Generated from protobuf field <code>int64 question_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setQuestionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->question_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string myanswer = 2;</code>
     * @return string
     */
    public function getMyanswer()
    {
        return $this->myanswer;
    }

    /**
     * Generated from protobuf field <code>string myanswer = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMyanswer($var)
    {
        GPBUtil::checkString($var, True);
        $this->myanswer = $var;

        return $this;
    }

}

