<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_seatwork.proto

namespace Cfwf\Micro_service\School_seatwork;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_seatwork.SearchSeatWorksRequest</code>
 */
class SearchSeatWorksRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 userid = 1;</code>
     */
    private $userid = 0;
    /**
     *每页条数
     *
     * Generated from protobuf field <code>int32 pagesize = 2;</code>
     */
    private $pagesize = 0;
    /**
     *当前页。如果>总页数，则返回最后一页的数据
     *
     * Generated from protobuf field <code>int32 page = 3;</code>
     */
    private $page = 0;
    /**
     *查询条件
     *
     * Generated from protobuf field <code>bool be_teacher = 4;</code>
     */
    private $be_teacher = false;
    /**
     *学校，必填
     *
     * Generated from protobuf field <code>int64 schoolid = 5;</code>
     */
    private $schoolid = 0;
    /**
     *年级，选填
     *
     * Generated from protobuf field <code>int32 grade = 6;</code>
     */
    private $grade = 0;
    /**
     *班级id，选填
     *
     * Generated from protobuf field <code>int64 classid = 7;</code>
     */
    private $classid = 0;
    /**
     *学科id，选填
     *
     * Generated from protobuf field <code>int32 subjectid = 8;</code>
     */
    private $subjectid = 0;

    public function __construct() {
        \GPBMetadata\SchoolSeatwork::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 userid = 1;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     * Generated from protobuf field <code>int64 userid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     *每页条数
     *
     * Generated from protobuf field <code>int32 pagesize = 2;</code>
     * @return int
     */
    public function getPagesize()
    {
        return $this->pagesize;
    }

    /**
     *每页条数
     *
     * Generated from protobuf field <code>int32 pagesize = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPagesize($var)
    {
        GPBUtil::checkInt32($var);
        $this->pagesize = $var;

        return $this;
    }

    /**
     *当前页。如果>总页数，则返回最后一页的数据
     *
     * Generated from protobuf field <code>int32 page = 3;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     *当前页。如果>总页数，则返回最后一页的数据
     *
     * Generated from protobuf field <code>int32 page = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     *查询条件
     *
     * Generated from protobuf field <code>bool be_teacher = 4;</code>
     * @return bool
     */
    public function getBeTeacher()
    {
        return $this->be_teacher;
    }

    /**
     *查询条件
     *
     * Generated from protobuf field <code>bool be_teacher = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setBeTeacher($var)
    {
        GPBUtil::checkBool($var);
        $this->be_teacher = $var;

        return $this;
    }

    /**
     *学校，必填
     *
     * Generated from protobuf field <code>int64 schoolid = 5;</code>
     * @return int|string
     */
    public function getSchoolid()
    {
        return $this->schoolid;
    }

    /**
     *学校，必填
     *
     * Generated from protobuf field <code>int64 schoolid = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSchoolid($var)
    {
        GPBUtil::checkInt64($var);
        $this->schoolid = $var;

        return $this;
    }

    /**
     *年级，选填
     *
     * Generated from protobuf field <code>int32 grade = 6;</code>
     * @return int
     */
    public function getGrade()
    {
        return $this->grade;
    }

    /**
     *年级，选填
     *
     * Generated from protobuf field <code>int32 grade = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setGrade($var)
    {
        GPBUtil::checkInt32($var);
        $this->grade = $var;

        return $this;
    }

    /**
     *班级id，选填
     *
     * Generated from protobuf field <code>int64 classid = 7;</code>
     * @return int|string
     */
    public function getClassid()
    {
        return $this->classid;
    }

    /**
     *班级id，选填
     *
     * Generated from protobuf field <code>int64 classid = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClassid($var)
    {
        GPBUtil::checkInt64($var);
        $this->classid = $var;

        return $this;
    }

    /**
     *学科id，选填
     *
     * Generated from protobuf field <code>int32 subjectid = 8;</code>
     * @return int
     */
    public function getSubjectid()
    {
        return $this->subjectid;
    }

    /**
     *学科id，选填
     *
     * Generated from protobuf field <code>int32 subjectid = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setSubjectid($var)
    {
        GPBUtil::checkInt32($var);
        $this->subjectid = $var;

        return $this;
    }

}

