<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_seatwork.proto

namespace Cfwf\Micro_service\School_seatwork;

/**
 *content 和 analysis 的格式
 *
 * Protobuf enum <code>Cfwf\Micro_service\School_seatwork\SeatWorkQuestion\CONTENT_TYPE</code>
 */
class SeatWorkQuestion_CONTENT_TYPE
{
    /**
     * Generated from protobuf enum <code>CONTENT_TYPE_NONE = 0;</code>
     */
    const CONTENT_TYPE_NONE = 0;
    /**
     *文字、小图片混合
     *
     * Generated from protobuf enum <code>CONTENT_TYPE_COMMON = 1;</code>
     */
    const CONTENT_TYPE_COMMON = 1;
    /**
     *一张大图片，无文字
     *
     * Generated from protobuf enum <code>CONTENT_TYPE_PIC_RES = 2;</code>
     */
    const CONTENT_TYPE_PIC_RES = 2;
}

