<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_seatwork.proto

namespace Cfwf\Micro_service\School_seatwork;

/**
 *做题状态
 *
 * Protobuf enum <code>Cfwf\Micro_service\School_seatwork\SeatWorkStatus\STATUS</code>
 */
class SeatWorkStatus_STATUS
{
    /**
     * Generated from protobuf enum <code>STATUS_NONE = 0;</code>
     */
    const STATUS_NONE = 0;
    /**
     * Generated from protobuf enum <code>STATUS_NOT_START = 1;</code>
     */
    const STATUS_NOT_START = 1;
    /**
     * Generated from protobuf enum <code>STATUS_DOING = 2;</code>
     */
    const STATUS_DOING = 2;
    /**
     * Generated from protobuf enum <code>STATUS_FINISH = 3;</code>
     */
    const STATUS_FINISH = 3;
    /**
     *超时未提交
     *
     * Generated from protobuf enum <code>STATUS_TIME_OUT = 4;</code>
     */
    const STATUS_TIME_OUT = 4;
}

