<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: view_stat.proto

namespace Cfwf\Micro_service\View_stat;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.view_stat.GetUserViewCountResponse</code>
 */
class GetUserViewCountResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.view_stat.RPC_CALL_RESULT result = 1;</code>
     */
    private $result = 0;
    /**
     *观看次数
     *
     * Generated from protobuf field <code>int32 count = 2;</code>
     */
    private $count = 0;
    /**
     *最后一次观看时间
     *
     * Generated from protobuf field <code>string time = 3;</code>
     */
    private $time = '';

    public function __construct() {
        \GPBMetadata\ViewStat::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.view_stat.RPC_CALL_RESULT result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.view_stat.RPC_CALL_RESULT result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\View_stat\RPC_CALL_RESULT::class);
        $this->result = $var;

        return $this;
    }

    /**
     *观看次数
     *
     * Generated from protobuf field <code>int32 count = 2;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     *观看次数
     *
     * Generated from protobuf field <code>int32 count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->count = $var;

        return $this;
    }

    /**
     *最后一次观看时间
     *
     * Generated from protobuf field <code>string time = 3;</code>
     * @return string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     *最后一次观看时间
     *
     * Generated from protobuf field <code>string time = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->time = $var;

        return $this;
    }

}

