<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: view_stat.proto

namespace Cfwf\Micro_service\View_stat;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.view_stat.InsertViewLogRequest</code>
 */
class InsertViewLogRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *所观看的资源的ID
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    private $id = 0;
    /**
     *观看者ID
     *
     * Generated from protobuf field <code>int64 userid = 2;</code>
     */
    private $userid = 0;
    /**
     *产品类型
     *
     * Generated from protobuf field <code>.cfwf.micro_service.view_stat.VIEW_PRODUCT_TYPE product_type = 3;</code>
     */
    private $product_type = 0;
    /**
     *观看设备
     *
     * Generated from protobuf field <code>.cfwf.micro_service.view_stat.DEVICE_TYPE device = 4;</code>
     */
    private $device = 0;

    public function __construct() {
        \GPBMetadata\ViewStat::initOnce();
        parent::__construct();
    }

    /**
     *所观看的资源的ID
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     *所观看的资源的ID
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     *观看者ID
     *
     * Generated from protobuf field <code>int64 userid = 2;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     *观看者ID
     *
     * Generated from protobuf field <code>int64 userid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     *产品类型
     *
     * Generated from protobuf field <code>.cfwf.micro_service.view_stat.VIEW_PRODUCT_TYPE product_type = 3;</code>
     * @return int
     */
    public function getProductType()
    {
        return $this->product_type;
    }

    /**
     *产品类型
     *
     * Generated from protobuf field <code>.cfwf.micro_service.view_stat.VIEW_PRODUCT_TYPE product_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setProductType($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\View_stat\VIEW_PRODUCT_TYPE::class);
        $this->product_type = $var;

        return $this;
    }

    /**
     *观看设备
     *
     * Generated from protobuf field <code>.cfwf.micro_service.view_stat.DEVICE_TYPE device = 4;</code>
     * @return int
     */
    public function getDevice()
    {
        return $this->device;
    }

    /**
     *观看设备
     *
     * Generated from protobuf field <code>.cfwf.micro_service.view_stat.DEVICE_TYPE device = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setDevice($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\View_stat\DEVICE_TYPE::class);
        $this->device = $var;

        return $this;
    }

}

