<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comment.proto

namespace Cfwf\Micro_service\Comment;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.comment.CommentItem</code>
 */
class CommentItem extends \Google\Protobuf\Internal\Message
{
    /**
     *评论发布者id 
     *
     * Generated from protobuf field <code>int64 userid = 1;</code>
     */
    private $userid = 0;
    /**
     *评论发布时间
     *
     * Generated from protobuf field <code>string time = 2;</code>
     */
    private $time = '';
    /**
     *评论内容
     *
     * Generated from protobuf field <code>string content = 3;</code>
     */
    private $content = '';
    /**
     *评论的id
     *
     * Generated from protobuf field <code>int64 id = 4;</code>
     */
    private $id = 0;

    public function __construct() {
        \GPBMetadata\Comment::initOnce();
        parent::__construct();
    }

    /**
     *评论发布者id 
     *
     * Generated from protobuf field <code>int64 userid = 1;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     *评论发布者id 
     *
     * Generated from protobuf field <code>int64 userid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     *评论发布时间
     *
     * Generated from protobuf field <code>string time = 2;</code>
     * @return string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     *评论发布时间
     *
     * Generated from protobuf field <code>string time = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->time = $var;

        return $this;
    }

    /**
     *评论内容
     *
     * Generated from protobuf field <code>string content = 3;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     *评论内容
     *
     * Generated from protobuf field <code>string content = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     *评论的id
     *
     * Generated from protobuf field <code>int64 id = 4;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     *评论的id
     *
     * Generated from protobuf field <code>int64 id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

}

