<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comment.proto

namespace Cfwf\Micro_service\Comment;

/**
 *评论类型
 *
 * Protobuf enum <code>Cfwf\Micro_service\Comment\COMMENT_TYPE</code>
 */
class COMMENT_TYPE
{
    /**
     * Generated from protobuf enum <code>COMMENT_TYPE_INIT = 0;</code>
     */
    const COMMENT_TYPE_INIT = 0;
    /**
     *班级点播课
     *
     * Generated from protobuf enum <code>COMMENT_TYPE_CLASS_WEIKE = 1;</code>
     */
    const COMMENT_TYPE_CLASS_WEIKE = 1;
}

