<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comment.proto

namespace Cfwf\Micro_service\Comment;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.comment.DeleteCommentRequest</code>
 */
class DeleteCommentRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *类型 
     *
     * Generated from protobuf field <code>.cfwf.micro_service.comment.COMMENT_TYPE type = 1;</code>
     */
    private $type = 0;
    /**
     *评论对象id
     *
     * Generated from protobuf field <code>int64 object_id = 2;</code>
     */
    private $object_id = 0;
    /**
     *评论的id
     *
     * Generated from protobuf field <code>int64 id = 3;</code>
     */
    private $id = 0;

    public function __construct() {
        \GPBMetadata\Comment::initOnce();
        parent::__construct();
    }

    /**
     *类型 
     *
     * Generated from protobuf field <code>.cfwf.micro_service.comment.COMMENT_TYPE type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *类型 
     *
     * Generated from protobuf field <code>.cfwf.micro_service.comment.COMMENT_TYPE type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\Comment\COMMENT_TYPE::class);
        $this->type = $var;

        return $this;
    }

    /**
     *评论对象id
     *
     * Generated from protobuf field <code>int64 object_id = 2;</code>
     * @return int|string
     */
    public function getObjectId()
    {
        return $this->object_id;
    }

    /**
     *评论对象id
     *
     * Generated from protobuf field <code>int64 object_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setObjectId($var)
    {
        GPBUtil::checkInt64($var);
        $this->object_id = $var;

        return $this;
    }

    /**
     *评论的id
     *
     * Generated from protobuf field <code>int64 id = 3;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     *评论的id
     *
     * Generated from protobuf field <code>int64 id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

}

