<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_teacher.proto

namespace Cfwf\Micro_service\School_teacher;

/**
 * Protobuf enum <code>Cfwf\Micro_service\School_teacher\APPROVE_PATTERNS</code>
 */
class APPROVE_PATTERNS
{
    /**
     *自动通过
     *
     * Generated from protobuf enum <code>APPROVE_PATTERNS_AUTO = 0;</code>
     */
    const APPROVE_PATTERNS_AUTO = 0;
    /**
     *人工审核 
     *
     * Generated from protobuf enum <code>APPROVE_PATTERNS_MANUAL = 1;</code>
     */
    const APPROVE_PATTERNS_MANUAL = 1;
}

