<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_teacher.proto

namespace Cfwf\Micro_service\School_teacher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *获取某老师信息
 *
 * Generated from protobuf message <code>cfwf.micro_service.school_teacher.GetTeacherInfoRequest</code>
 */
class GetTeacherInfoRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *老师id，必填
     *
     * Generated from protobuf field <code>fixed64 teacherid = 1;</code>
     */
    private $teacherid = 0;
    /**
     *学校id，可不填。如果不填，则返回该老师在所有学校的任课信息：允许老师属于多个学校
     *
     * Generated from protobuf field <code>fixed64 schoolid = 2;</code>
     */
    private $schoolid = 0;

    public function __construct() {
        \GPBMetadata\SchoolTeacher::initOnce();
        parent::__construct();
    }

    /**
     *老师id，必填
     *
     * Generated from protobuf field <code>fixed64 teacherid = 1;</code>
     * @return int|string
     */
    public function getTeacherid()
    {
        return $this->teacherid;
    }

    /**
     *老师id，必填
     *
     * Generated from protobuf field <code>fixed64 teacherid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTeacherid($var)
    {
        GPBUtil::checkUint64($var);
        $this->teacherid = $var;

        return $this;
    }

    /**
     *学校id，可不填。如果不填，则返回该老师在所有学校的任课信息：允许老师属于多个学校
     *
     * Generated from protobuf field <code>fixed64 schoolid = 2;</code>
     * @return int|string
     */
    public function getSchoolid()
    {
        return $this->schoolid;
    }

    /**
     *学校id，可不填。如果不填，则返回该老师在所有学校的任课信息：允许老师属于多个学校
     *
     * Generated from protobuf field <code>fixed64 schoolid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSchoolid($var)
    {
        GPBUtil::checkUint64($var);
        $this->schoolid = $var;

        return $this;
    }

}

