<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_teacher.proto

namespace Cfwf\Micro_service\School_teacher;

use Google\Protobuf\Internal\GPBUtil;

/**
 *获取老师列表(分页返回)
 *
 * Generated from protobuf message <code>cfwf.micro_service.school_teacher.SearchTeacherRequest</code>
 */
class SearchTeacherRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *每页条数
     *
     * Generated from protobuf field <code>int32 pagesize = 1;</code>
     */
    private $pagesize = 0;
    /**
     *当前页。如果>总页数，则返回最后一页的数据
     *
     * Generated from protobuf field <code>int32 page = 2;</code>
     */
    private $page = 0;
    /**
     *学校id，必填
     *
     * Generated from protobuf field <code>fixed64 schoolid = 3;</code>
     */
    private $schoolid = 0;
    /**
     *老师类型：0=不限 1=任课教师 2=非任课教师。当查询非任课教师时，grade,subject,classid将被忽略
     *
     * Generated from protobuf field <code>int32 teacher_type = 4;</code>
     */
    private $teacher_type = 0;
    /**
     *所教的届: 可多个: 2016,2017 ...
     *
     * Generated from protobuf field <code>string grade_year = 5;</code>
     */
    private $grade_year = '';
    /**
     *年级列表: 1,2,3..   空字符串表示不限年级。 
     *
     * Generated from protobuf field <code>string grade = 6;</code>
     */
    private $grade = '';
    /**
     *科目，可为0，表示不限科目
     *
     * Generated from protobuf field <code>int32 subject = 7;</code>
     */
    private $subject = 0;
    /**
     *班级id，可为0，表示不限班级
     *
     * Generated from protobuf field <code>fixed64 classid = 8;</code>
     */
    private $classid = 0;
    /**
     *姓名/帐号 关键字   
     *
     * Generated from protobuf field <code>string keyword = 9;</code>
     */
    private $keyword = '';

    public function __construct() {
        \GPBMetadata\SchoolTeacher::initOnce();
        parent::__construct();
    }

    /**
     *每页条数
     *
     * Generated from protobuf field <code>int32 pagesize = 1;</code>
     * @return int
     */
    public function getPagesize()
    {
        return $this->pagesize;
    }

    /**
     *每页条数
     *
     * Generated from protobuf field <code>int32 pagesize = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPagesize($var)
    {
        GPBUtil::checkInt32($var);
        $this->pagesize = $var;

        return $this;
    }

    /**
     *当前页。如果>总页数，则返回最后一页的数据
     *
     * Generated from protobuf field <code>int32 page = 2;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     *当前页。如果>总页数，则返回最后一页的数据
     *
     * Generated from protobuf field <code>int32 page = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     *学校id，必填
     *
     * Generated from protobuf field <code>fixed64 schoolid = 3;</code>
     * @return int|string
     */
    public function getSchoolid()
    {
        return $this->schoolid;
    }

    /**
     *学校id，必填
     *
     * Generated from protobuf field <code>fixed64 schoolid = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSchoolid($var)
    {
        GPBUtil::checkUint64($var);
        $this->schoolid = $var;

        return $this;
    }

    /**
     *老师类型：0=不限 1=任课教师 2=非任课教师。当查询非任课教师时，grade,subject,classid将被忽略
     *
     * Generated from protobuf field <code>int32 teacher_type = 4;</code>
     * @return int
     */
    public function getTeacherType()
    {
        return $this->teacher_type;
    }

    /**
     *老师类型：0=不限 1=任课教师 2=非任课教师。当查询非任课教师时，grade,subject,classid将被忽略
     *
     * Generated from protobuf field <code>int32 teacher_type = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setTeacherType($var)
    {
        GPBUtil::checkInt32($var);
        $this->teacher_type = $var;

        return $this;
    }

    /**
     *所教的届: 可多个: 2016,2017 ...
     *
     * Generated from protobuf field <code>string grade_year = 5;</code>
     * @return string
     */
    public function getGradeYear()
    {
        return $this->grade_year;
    }

    /**
     *所教的届: 可多个: 2016,2017 ...
     *
     * Generated from protobuf field <code>string grade_year = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setGradeYear($var)
    {
        GPBUtil::checkString($var, True);
        $this->grade_year = $var;

        return $this;
    }

    /**
     *年级列表: 1,2,3..   空字符串表示不限年级。 
     *
     * Generated from protobuf field <code>string grade = 6;</code>
     * @return string
     */
    public function getGrade()
    {
        return $this->grade;
    }

    /**
     *年级列表: 1,2,3..   空字符串表示不限年级。 
     *
     * Generated from protobuf field <code>string grade = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setGrade($var)
    {
        GPBUtil::checkString($var, True);
        $this->grade = $var;

        return $this;
    }

    /**
     *科目，可为0，表示不限科目
     *
     * Generated from protobuf field <code>int32 subject = 7;</code>
     * @return int
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     *科目，可为0，表示不限科目
     *
     * Generated from protobuf field <code>int32 subject = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkInt32($var);
        $this->subject = $var;

        return $this;
    }

    /**
     *班级id，可为0，表示不限班级
     *
     * Generated from protobuf field <code>fixed64 classid = 8;</code>
     * @return int|string
     */
    public function getClassid()
    {
        return $this->classid;
    }

    /**
     *班级id，可为0，表示不限班级
     *
     * Generated from protobuf field <code>fixed64 classid = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClassid($var)
    {
        GPBUtil::checkUint64($var);
        $this->classid = $var;

        return $this;
    }

    /**
     *姓名/帐号 关键字   
     *
     * Generated from protobuf field <code>string keyword = 9;</code>
     * @return string
     */
    public function getKeyword()
    {
        return $this->keyword;
    }

    /**
     *姓名/帐号 关键字   
     *
     * Generated from protobuf field <code>string keyword = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyword($var)
    {
        GPBUtil::checkString($var, True);
        $this->keyword = $var;

        return $this;
    }

}

