<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_teacher.proto

namespace Cfwf\Micro_service\School_teacher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_teacher.SetTeacherClassInfoByJsonRequest</code>
 */
class SetTeacherClassInfoByJsonRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *学校id，必填
     *
     * Generated from protobuf field <code>fixed64 schoolid = 1;</code>
     */
    private $schoolid = 0;
    /**
     *老师id，必填
     *
     * Generated from protobuf field <code>fixed64 teacherid = 2;</code>
     */
    private $teacherid = 0;
    /**
     *是否任课: 若原先为任课，改为不认课，则原先所有任课信息将被清除
     *
     * Generated from protobuf field <code>bool is_course_teacher = 3;</code>
     */
    private $is_course_teacher = false;
    /**
     * =true: 增加所教班级科目，原设置不变，忽略相同项。 =fasle:  将原设置覆盖为新设置
     *
     * Generated from protobuf field <code>bool is_addnew = 4;</code>
     */
    private $is_addnew = false;
    /**
     * json格式，见TeacherInfo.teach_info。
     *
     * Generated from protobuf field <code>string teach_info = 5;</code>
     */
    private $teach_info = '';
    /**
     * Generated from protobuf field <code>fixed64 operatorid = 6;</code>
     */
    private $operatorid = 0;

    public function __construct() {
        \GPBMetadata\SchoolTeacher::initOnce();
        parent::__construct();
    }

    /**
     *学校id，必填
     *
     * Generated from protobuf field <code>fixed64 schoolid = 1;</code>
     * @return int|string
     */
    public function getSchoolid()
    {
        return $this->schoolid;
    }

    /**
     *学校id，必填
     *
     * Generated from protobuf field <code>fixed64 schoolid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSchoolid($var)
    {
        GPBUtil::checkUint64($var);
        $this->schoolid = $var;

        return $this;
    }

    /**
     *老师id，必填
     *
     * Generated from protobuf field <code>fixed64 teacherid = 2;</code>
     * @return int|string
     */
    public function getTeacherid()
    {
        return $this->teacherid;
    }

    /**
     *老师id，必填
     *
     * Generated from protobuf field <code>fixed64 teacherid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTeacherid($var)
    {
        GPBUtil::checkUint64($var);
        $this->teacherid = $var;

        return $this;
    }

    /**
     *是否任课: 若原先为任课，改为不认课，则原先所有任课信息将被清除
     *
     * Generated from protobuf field <code>bool is_course_teacher = 3;</code>
     * @return bool
     */
    public function getIsCourseTeacher()
    {
        return $this->is_course_teacher;
    }

    /**
     *是否任课: 若原先为任课，改为不认课，则原先所有任课信息将被清除
     *
     * Generated from protobuf field <code>bool is_course_teacher = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsCourseTeacher($var)
    {
        GPBUtil::checkBool($var);
        $this->is_course_teacher = $var;

        return $this;
    }

    /**
     * =true: 增加所教班级科目，原设置不变，忽略相同项。 =fasle:  将原设置覆盖为新设置
     *
     * Generated from protobuf field <code>bool is_addnew = 4;</code>
     * @return bool
     */
    public function getIsAddnew()
    {
        return $this->is_addnew;
    }

    /**
     * =true: 增加所教班级科目，原设置不变，忽略相同项。 =fasle:  将原设置覆盖为新设置
     *
     * Generated from protobuf field <code>bool is_addnew = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAddnew($var)
    {
        GPBUtil::checkBool($var);
        $this->is_addnew = $var;

        return $this;
    }

    /**
     * json格式，见TeacherInfo.teach_info。
     *
     * Generated from protobuf field <code>string teach_info = 5;</code>
     * @return string
     */
    public function getTeachInfo()
    {
        return $this->teach_info;
    }

    /**
     * json格式，见TeacherInfo.teach_info。
     *
     * Generated from protobuf field <code>string teach_info = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTeachInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->teach_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed64 operatorid = 6;</code>
     * @return int|string
     */
    public function getOperatorid()
    {
        return $this->operatorid;
    }

    /**
     * Generated from protobuf field <code>fixed64 operatorid = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOperatorid($var)
    {
        GPBUtil::checkUint64($var);
        $this->operatorid = $var;

        return $this;
    }

}

