<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_teacher.proto

namespace Cfwf\Micro_service\School_teacher;

use Google\Protobuf\Internal\GPBUtil;

/**
 *TeacherInfo：老师信息。
 *
 * Generated from protobuf message <code>cfwf.micro_service.school_teacher.TeacherInfo</code>
 */
class TeacherInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed64 userid = 1;</code>
     */
    private $userid = 0;
    /**
     *学校id
     *
     * Generated from protobuf field <code>fixed64 schoolid = 2;</code>
     */
    private $schoolid = 0;
    /**
     *姓名
     *
     * Generated from protobuf field <code>string username = 3;</code>
     */
    private $username = '';
    /**
     *性别： 男/女
     *
     * Generated from protobuf field <code>.cfwf.micro_service.school_teacher.USER_SEX sex = 4;</code>
     */
    private $sex = 0;
    /**
     *联系方式
     *
     * Generated from protobuf field <code>string tel = 5;</code>
     */
    private $tel = '';
    /**
     *是否任课教师
     *
     * Generated from protobuf field <code>bool is_course_teacher = 6;</code>
     */
    private $is_course_teacher = false;
    /**
     *任教信息，和TeacherApplyInfo格式相同 [{"grade_year":2012,"period":1,"classid":10002,"classno":1,"subject":"1,2"},{"grade_year":2012,"period":1,"classid":10002,"classno":1,"subject":"1,2"}]
     *
     * Generated from protobuf field <code>string teach_info = 7;</code>
     */
    private $teach_info = '';

    public function __construct() {
        \GPBMetadata\SchoolTeacher::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>fixed64 userid = 1;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     * Generated from protobuf field <code>fixed64 userid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkUint64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     *学校id
     *
     * Generated from protobuf field <code>fixed64 schoolid = 2;</code>
     * @return int|string
     */
    public function getSchoolid()
    {
        return $this->schoolid;
    }

    /**
     *学校id
     *
     * Generated from protobuf field <code>fixed64 schoolid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSchoolid($var)
    {
        GPBUtil::checkUint64($var);
        $this->schoolid = $var;

        return $this;
    }

    /**
     *姓名
     *
     * Generated from protobuf field <code>string username = 3;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     *姓名
     *
     * Generated from protobuf field <code>string username = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     *性别： 男/女
     *
     * Generated from protobuf field <code>.cfwf.micro_service.school_teacher.USER_SEX sex = 4;</code>
     * @return int
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     *性别： 男/女
     *
     * Generated from protobuf field <code>.cfwf.micro_service.school_teacher.USER_SEX sex = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\School_teacher\USER_SEX::class);
        $this->sex = $var;

        return $this;
    }

    /**
     *联系方式
     *
     * Generated from protobuf field <code>string tel = 5;</code>
     * @return string
     */
    public function getTel()
    {
        return $this->tel;
    }

    /**
     *联系方式
     *
     * Generated from protobuf field <code>string tel = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTel($var)
    {
        GPBUtil::checkString($var, True);
        $this->tel = $var;

        return $this;
    }

    /**
     *是否任课教师
     *
     * Generated from protobuf field <code>bool is_course_teacher = 6;</code>
     * @return bool
     */
    public function getIsCourseTeacher()
    {
        return $this->is_course_teacher;
    }

    /**
     *是否任课教师
     *
     * Generated from protobuf field <code>bool is_course_teacher = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsCourseTeacher($var)
    {
        GPBUtil::checkBool($var);
        $this->is_course_teacher = $var;

        return $this;
    }

    /**
     *任教信息，和TeacherApplyInfo格式相同 [{"grade_year":2012,"period":1,"classid":10002,"classno":1,"subject":"1,2"},{"grade_year":2012,"period":1,"classid":10002,"classno":1,"subject":"1,2"}]
     *
     * Generated from protobuf field <code>string teach_info = 7;</code>
     * @return string
     */
    public function getTeachInfo()
    {
        return $this->teach_info;
    }

    /**
     *任教信息，和TeacherApplyInfo格式相同 [{"grade_year":2012,"period":1,"classid":10002,"classno":1,"subject":"1,2"},{"grade_year":2012,"period":1,"classid":10002,"classno":1,"subject":"1,2"}]
     *
     * Generated from protobuf field <code>string teach_info = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTeachInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->teach_info = $var;

        return $this;
    }

}

