<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_teacher.proto

namespace Cfwf\Micro_service\School_teacher;

/**
 *教师申请信息
 *
 * Protobuf enum <code>Cfwf\Micro_service\School_teacher\USER_SEX</code>
 */
class USER_SEX
{
    /**
     * Generated from protobuf enum <code>USER_SEX_INIT = 0;</code>
     */
    const USER_SEX_INIT = 0;
    /**
     * Generated from protobuf enum <code>USER_SEX_GIRL = 1;</code>
     */
    const USER_SEX_GIRL = 1;
    /**
     * Generated from protobuf enum <code>USER_SEX_BOY = 2;</code>
     */
    const USER_SEX_BOY = 2;
}

