<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace Cfwf\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *一般消息，客户端可在上线后调用 im::kCmdGetUnreceivedMessage指令获取未收到的离线消息
 *
 * Generated from protobuf message <code>cfwf.message.CommonMessage</code>
 */
class CommonMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 msgid = 1;</code>
     */
    private $msgid = 0;
    /**
     *MESSAGE_TYPE     
     *
     * Generated from protobuf field <code>.cfwf.message.CommonMessage.MESSAGE_TYPE msg_type = 2;</code>
     */
    private $msg_type = 0;
    /**
     * Generated from protobuf field <code>int64 from_userid = 3;</code>
     */
    private $from_userid = 0;
    /**
     * Generated from protobuf field <code>int64 send_to = 4;</code>
     */
    private $send_to = 0;
    /**
     * Generated from protobuf field <code>.cfwf.message.CommonMessage.CONTENT_TYPE content_type = 5;</code>
     */
    private $content_type = 0;
    /**
     * Generated from protobuf field <code>string content = 6;</code>
     */
    private $content = '';
    /**
     *文件和图片(根据filename后缀判断)，json格式：[{"resid":file_resid,"filesize":filesize,"filename":filename}]
     *
     * Generated from protobuf field <code>string attachment_file = 7;</code>
     */
    private $attachment_file = '';
    /**
     *音视频(根据filename后缀判断)，json格式：[{"resid":file_resid,"filesize":filesize,"duration":duration,"filename":filename}]
     *
     * Generated from protobuf field <code>string attachment_audio = 8;</code>
     */
    private $attachment_audio = '';
    /**
     *连接到特定页面    
     *
     * Generated from protobuf field <code>string link_url = 9;</code>
     */
    private $link_url = '';
    /**
     * Generated from protobuf field <code>string send_time = 10;</code>
     */
    private $send_time = '';
    /**
     *需要接收方确认阅读状态。 此类消息显示时，需要显示“阅读确认”的按钮，用户点击按钮时   
     *
     * Generated from protobuf field <code>bool need_read_confirm = 11;</code>
     */
    private $need_read_confirm = false;

    public function __construct() {
        \GPBMetadata\Message::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 msgid = 1;</code>
     * @return int|string
     */
    public function getMsgid()
    {
        return $this->msgid;
    }

    /**
     * Generated from protobuf field <code>int64 msgid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgid($var)
    {
        GPBUtil::checkInt64($var);
        $this->msgid = $var;

        return $this;
    }

    /**
     *MESSAGE_TYPE     
     *
     * Generated from protobuf field <code>.cfwf.message.CommonMessage.MESSAGE_TYPE msg_type = 2;</code>
     * @return int
     */
    public function getMsgType()
    {
        return $this->msg_type;
    }

    /**
     *MESSAGE_TYPE     
     *
     * Generated from protobuf field <code>.cfwf.message.CommonMessage.MESSAGE_TYPE msg_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMsgType($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Message\CommonMessage_MESSAGE_TYPE::class);
        $this->msg_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 from_userid = 3;</code>
     * @return int|string
     */
    public function getFromUserid()
    {
        return $this->from_userid;
    }

    /**
     * Generated from protobuf field <code>int64 from_userid = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFromUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->from_userid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 send_to = 4;</code>
     * @return int|string
     */
    public function getSendTo()
    {
        return $this->send_to;
    }

    /**
     * Generated from protobuf field <code>int64 send_to = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSendTo($var)
    {
        GPBUtil::checkInt64($var);
        $this->send_to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cfwf.message.CommonMessage.CONTENT_TYPE content_type = 5;</code>
     * @return int
     */
    public function getContentType()
    {
        return $this->content_type;
    }

    /**
     * Generated from protobuf field <code>.cfwf.message.CommonMessage.CONTENT_TYPE content_type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Message\CommonMessage_CONTENT_TYPE::class);
        $this->content_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string content = 6;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Generated from protobuf field <code>string content = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     *文件和图片(根据filename后缀判断)，json格式：[{"resid":file_resid,"filesize":filesize,"filename":filename}]
     *
     * Generated from protobuf field <code>string attachment_file = 7;</code>
     * @return string
     */
    public function getAttachmentFile()
    {
        return $this->attachment_file;
    }

    /**
     *文件和图片(根据filename后缀判断)，json格式：[{"resid":file_resid,"filesize":filesize,"filename":filename}]
     *
     * Generated from protobuf field <code>string attachment_file = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAttachmentFile($var)
    {
        GPBUtil::checkString($var, True);
        $this->attachment_file = $var;

        return $this;
    }

    /**
     *音视频(根据filename后缀判断)，json格式：[{"resid":file_resid,"filesize":filesize,"duration":duration,"filename":filename}]
     *
     * Generated from protobuf field <code>string attachment_audio = 8;</code>
     * @return string
     */
    public function getAttachmentAudio()
    {
        return $this->attachment_audio;
    }

    /**
     *音视频(根据filename后缀判断)，json格式：[{"resid":file_resid,"filesize":filesize,"duration":duration,"filename":filename}]
     *
     * Generated from protobuf field <code>string attachment_audio = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setAttachmentAudio($var)
    {
        GPBUtil::checkString($var, True);
        $this->attachment_audio = $var;

        return $this;
    }

    /**
     *连接到特定页面    
     *
     * Generated from protobuf field <code>string link_url = 9;</code>
     * @return string
     */
    public function getLinkUrl()
    {
        return $this->link_url;
    }

    /**
     *连接到特定页面    
     *
     * Generated from protobuf field <code>string link_url = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setLinkUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->link_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string send_time = 10;</code>
     * @return string
     */
    public function getSendTime()
    {
        return $this->send_time;
    }

    /**
     * Generated from protobuf field <code>string send_time = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setSendTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->send_time = $var;

        return $this;
    }

    /**
     *需要接收方确认阅读状态。 此类消息显示时，需要显示“阅读确认”的按钮，用户点击按钮时   
     *
     * Generated from protobuf field <code>bool need_read_confirm = 11;</code>
     * @return bool
     */
    public function getNeedReadConfirm()
    {
        return $this->need_read_confirm;
    }

    /**
     *需要接收方确认阅读状态。 此类消息显示时，需要显示“阅读确认”的按钮，用户点击按钮时   
     *
     * Generated from protobuf field <code>bool need_read_confirm = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setNeedReadConfirm($var)
    {
        GPBUtil::checkBool($var);
        $this->need_read_confirm = $var;

        return $this;
    }

}

