<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace Cfwf\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *计数型消息。客户端可在上线后调用 im::kCmdGetCounterMessageStat 指令获取如新班级微课、随堂检测灯光计数统计信息 
 *
 * Generated from protobuf message <code>cfwf.message.CounterMessage</code>
 */
class CounterMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cfwf.message.CounterMessage.MESSAGE_TYPE msg_type = 1;</code>
     */
    private $msg_type = 0;
    /**
     * Generated from protobuf field <code>.cfwf.message.CounterMessage.TYPE type = 2;</code>
     */
    private $type = 0;
    /**
     *当 set_type!=kSetCountZero时， 增加或减少的值
     *
     * Generated from protobuf field <code>int32 count = 3;</code>
     */
    private $count = 0;

    public function __construct() {
        \GPBMetadata\Message::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.cfwf.message.CounterMessage.MESSAGE_TYPE msg_type = 1;</code>
     * @return int
     */
    public function getMsgType()
    {
        return $this->msg_type;
    }

    /**
     * Generated from protobuf field <code>.cfwf.message.CounterMessage.MESSAGE_TYPE msg_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMsgType($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Message\CounterMessage_MESSAGE_TYPE::class);
        $this->msg_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cfwf.message.CounterMessage.TYPE type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.cfwf.message.CounterMessage.TYPE type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Message\CounterMessage_TYPE::class);
        $this->type = $var;

        return $this;
    }

    /**
     *当 set_type!=kSetCountZero时， 增加或减少的值
     *
     * Generated from protobuf field <code>int32 count = 3;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     *当 set_type!=kSetCountZero时， 增加或减少的值
     *
     * Generated from protobuf field <code>int32 count = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->count = $var;

        return $this;
    }

}

