<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace Cfwf\Message;

/**
 * Protobuf enum <code>Cfwf\Message\CounterMessage\MESSAGE_TYPE</code>
 */
class CounterMessage_MESSAGE_TYPE
{
    /**
     *不被使用
     *
     * Generated from protobuf enum <code>kMsgTypeNone = 0;</code>
     */
    const kMsgTypeNone = 0;
    /**
     *微课
     *
     * Generated from protobuf enum <code>kMsgTypeSchoolWeike = 1;</code>
     */
    const kMsgTypeSchoolWeike = 1;
    /**
     *随堂检测
     *
     * Generated from protobuf enum <code>kMsgTypeSchoolSeatwork = 2;</code>
     */
    const kMsgTypeSchoolSeatwork = 2;
    /**
     *家庭作业
     *
     * Generated from protobuf enum <code>kMsgTypeSchoolHomework = 3;</code>
     */
    const kMsgTypeSchoolHomework = 3;
    /**
     *校内通知
     *
     * Generated from protobuf enum <code>kMsgTypeSchoolInform = 4;</code>
     */
    const kMsgTypeSchoolInform = 4;
}

