<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace Cfwf\Message;

/**
 * Protobuf enum <code>Cfwf\Message\OnlineMessage\MESSAGE_TYPE</code>
 */
class OnlineMessage_MESSAGE_TYPE
{
    /**
     *不被使用
     *
     * Generated from protobuf enum <code>kMsgTypeNone = 0;</code>
     */
    const kMsgTypeNone = 0;
    /**
     *自己信息变化
     *
     * Generated from protobuf enum <code>kMsgTypeMyInfoChange = 1;</code>
     */
    const kMsgTypeMyInfoChange = 1;
    /**
     *余额发生变动
     *
     * Generated from protobuf enum <code>kMsgTypeMyMoneyChange = 2;</code>
     */
    const kMsgTypeMyMoneyChange = 2;
    /**
     *积分发生变动
     *
     * Generated from protobuf enum <code>kMsgTypeMyScoreChange = 3;</code>
     */
    const kMsgTypeMyScoreChange = 3;
    /**
     *其他设备上增加了好友。     由 im_friend 微服务发出
     *
     * Generated from protobuf enum <code>kMsgTypeHasAddFriend = 11;</code>
     */
    const kMsgTypeHasAddFriend = 11;
    /**
     *其他设备上删除了好友。     由 im_friend 微服务发出
     *
     * Generated from protobuf enum <code>kMsgTypeHasRemoveFriend = 12;</code>
     */
    const kMsgTypeHasRemoveFriend = 12;
    /**
     *其他设备上处理了好友申请。 由 im_friend 微服务发出
     *
     * Generated from protobuf enum <code>kMsgTypeHasDisposeFriendApply = 13;</code>
     */
    const kMsgTypeHasDisposeFriendApply = 13;
    /**
     *其他设备上将好友拉黑       由 im_friend 微服务发出
     *
     * Generated from protobuf enum <code>kMsgTypeHasAddUserToBlackList = 14;</code>
     */
    const kMsgTypeHasAddUserToBlackList = 14;
    /**
     *（群）好友信息变化
     *
     * Generated from protobuf enum <code>kMsgTypeFriendInfoChange = 21;</code>
     */
    const kMsgTypeFriendInfoChange = 21;
    /**
     *好友上下线   由 online_status 微服务发出。 注意：离线消息不能马上发出，应等待一个超时时间后，客户端未重新上线后再发出，防止因客户端切换网络时频繁触发
     *
     * Generated from protobuf enum <code>kMsgTypeFriendOnlineStatusChange = 22;</code>
     */
    const kMsgTypeFriendOnlineStatusChange = 22;
    /**
     *群成员增加    由 im_group 微服务发出
     *
     * Generated from protobuf enum <code>kMsgTypeGroupAddMember = 23;</code>
     */
    const kMsgTypeGroupAddMember = 23;
    /**
     *群成员减少    由 im_group 微服务发出	
     *
     * Generated from protobuf enum <code>kMsgTypeGroupMemberLeave = 24;</code>
     */
    const kMsgTypeGroupMemberLeave = 24;
}

