<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_class.proto

namespace Cfwf\Micro_service\School_class;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *创建班级 CreateSchoolClass。如果班级不存在，则创建之，返回成功，若已存在，则不创建，返回成功
 *
 * Generated from protobuf message <code>cfwf.micro_service.school_class.CreateSchoolClassRequest</code>
 */
class CreateSchoolClassRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed64 operatorid = 1;</code>
     */
    private $operatorid = 0;
    /**
     *SchoolClassInfo.classid 可由调用者指定(必须全局唯一)，也可置零，由微服务自己生成。 如果指定id，则检查是否已存在相同id，若存在则返回错误。 不会创建归档的班级，忽略SchoolClassInfo.be_archived字段
     *
     * Generated from protobuf field <code>.cfwf.micro_service.school_class.SchoolClassInfo info = 2;</code>
     */
    private $info = null;

    public function __construct() {
        \GPBMetadata\SchoolClass::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>fixed64 operatorid = 1;</code>
     * @return int|string
     */
    public function getOperatorid()
    {
        return $this->operatorid;
    }

    /**
     * Generated from protobuf field <code>fixed64 operatorid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOperatorid($var)
    {
        GPBUtil::checkUint64($var);
        $this->operatorid = $var;

        return $this;
    }

    /**
     *SchoolClassInfo.classid 可由调用者指定(必须全局唯一)，也可置零，由微服务自己生成。 如果指定id，则检查是否已存在相同id，若存在则返回错误。 不会创建归档的班级，忽略SchoolClassInfo.be_archived字段
     *
     * Generated from protobuf field <code>.cfwf.micro_service.school_class.SchoolClassInfo info = 2;</code>
     * @return \Cfwf\Micro_service\School_class\SchoolClassInfo
     */
    public function getInfo()
    {
        return $this->info;
    }

    /**
     *SchoolClassInfo.classid 可由调用者指定(必须全局唯一)，也可置零，由微服务自己生成。 如果指定id，则检查是否已存在相同id，若存在则返回错误。 不会创建归档的班级，忽略SchoolClassInfo.be_archived字段
     *
     * Generated from protobuf field <code>.cfwf.micro_service.school_class.SchoolClassInfo info = 2;</code>
     * @param \Cfwf\Micro_service\School_class\SchoolClassInfo $var
     * @return $this
     */
    public function setInfo($var)
    {
        GPBUtil::checkMessage($var, \Cfwf\Micro_service\School_class\SchoolClassInfo::class);
        $this->info = $var;

        return $this;
    }

}

