<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_class.proto

namespace Cfwf\Micro_service\School_class;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_class.GetSchoolClassesInfoByIdRequest</code>
 */
class GetSchoolClassesInfoByIdRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated fixed64 classid = 1;</code>
     */
    private $classid;

    public function __construct() {
        \GPBMetadata\SchoolClass::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated fixed64 classid = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getClassid()
    {
        return $this->classid;
    }

    /**
     * Generated from protobuf field <code>repeated fixed64 classid = 1;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setClassid($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FIXED64);
        $this->classid = $arr;

        return $this;
    }

}

