<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_class.proto

namespace Cfwf\Micro_service\School_class;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_class.GetSchoolClassesInfoRequest</code>
 */
class GetSchoolClassesInfoRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .cfwf.micro_service.school_class.SimpleClassInfo class_infos = 1;</code>
     */
    private $class_infos;
    /**
     *如果不存在该班级是否自动创建
     *
     * Generated from protobuf field <code>bool create_if_not_exist = 2;</code>
     */
    private $create_if_not_exist = false;
    /**
     * Generated from protobuf field <code>fixed64 operatorid = 3;</code>
     */
    private $operatorid = 0;

    public function __construct() {
        \GPBMetadata\SchoolClass::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .cfwf.micro_service.school_class.SimpleClassInfo class_infos = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getClassInfos()
    {
        return $this->class_infos;
    }

    /**
     * Generated from protobuf field <code>repeated .cfwf.micro_service.school_class.SimpleClassInfo class_infos = 1;</code>
     * @param \Cfwf\Micro_service\School_class\SimpleClassInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setClassInfos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cfwf\Micro_service\School_class\SimpleClassInfo::class);
        $this->class_infos = $arr;

        return $this;
    }

    /**
     *如果不存在该班级是否自动创建
     *
     * Generated from protobuf field <code>bool create_if_not_exist = 2;</code>
     * @return bool
     */
    public function getCreateIfNotExist()
    {
        return $this->create_if_not_exist;
    }

    /**
     *如果不存在该班级是否自动创建
     *
     * Generated from protobuf field <code>bool create_if_not_exist = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setCreateIfNotExist($var)
    {
        GPBUtil::checkBool($var);
        $this->create_if_not_exist = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed64 operatorid = 3;</code>
     * @return int|string
     */
    public function getOperatorid()
    {
        return $this->operatorid;
    }

    /**
     * Generated from protobuf field <code>fixed64 operatorid = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOperatorid($var)
    {
        GPBUtil::checkUint64($var);
        $this->operatorid = $var;

        return $this;
    }

}

