<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_class.proto

namespace Cfwf\Micro_service\School_class;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *获取某班级信息 GetSchoolClassInfo 、 GetSchoolClassInfoById： 不会查找已归档的班级
 *
 * Generated from protobuf message <code>cfwf.micro_service.school_class.GetSchoolClassInfoByIdRequest</code>
 */
class GetSchoolClassInfoByIdRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *班级id
     *
     * Generated from protobuf field <code>fixed64 classid = 1;</code>
     */
    private $classid = 0;

    public function __construct() {
        \GPBMetadata\SchoolClass::initOnce();
        parent::__construct();
    }

    /**
     *班级id
     *
     * Generated from protobuf field <code>fixed64 classid = 1;</code>
     * @return int|string
     */
    public function getClassid()
    {
        return $this->classid;
    }

    /**
     *班级id
     *
     * Generated from protobuf field <code>fixed64 classid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClassid($var)
    {
        GPBUtil::checkUint64($var);
        $this->classid = $var;

        return $this;
    }

}

