<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sms.proto

namespace Cfwf\Micro_service\Sms;

/**
 *验证码类型
 *
 * Protobuf enum <code>Cfwf\Micro_service\Sms\CODE_TYPE</code>
 */
class CODE_TYPE
{
    /**
     * Generated from protobuf enum <code>CODE_TYPE_INIT = 0;</code>
     */
    const CODE_TYPE_INIT = 0;
    /**
     *注册
     *
     * Generated from protobuf enum <code>CODE_TYPE_REGISTER = 1;</code>
     */
    const CODE_TYPE_REGISTER = 1;
    /**
     *找回密码
     *
     * Generated from protobuf enum <code>CODE_TYPE_RETRIEVE_PASSWORD = 2;</code>
     */
    const CODE_TYPE_RETRIEVE_PASSWORD = 2;
    /**
     *绑定手机号
     *
     * Generated from protobuf enum <code>CODE_TYPE_BIND_MOBILEPHONE = 3;</code>
     */
    const CODE_TYPE_BIND_MOBILEPHONE = 3;
    /**
     *更换手机时，给老手机发送验证码
     *
     * Generated from protobuf enum <code>CODE_TYPE_CHECK_FORMER_MOBILEPHONE = 4;</code>
     */
    const CODE_TYPE_CHECK_FORMER_MOBILEPHONE = 4;
    /**
     *绑定提现账户
     *
     * Generated from protobuf enum <code>CODE_TYPE_BIND_WITHDRAWALS_ACCOUNT = 5;</code>
     */
    const CODE_TYPE_BIND_WITHDRAWALS_ACCOUNT = 5;
    /**
     *提现
     *
     * Generated from protobuf enum <code>CODE_TYPE_WITHDRAWALS = 6;</code>
     */
    const CODE_TYPE_WITHDRAWALS = 6;
}

