<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_weike.proto

namespace Cfwf\Micro_service\School_weike;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_weike.ClassWeikeViewItem</code>
 */
class ClassWeikeViewItem extends \Google\Protobuf\Internal\Message
{
    /**
     *观看者id
     *
     * Generated from protobuf field <code>int64 userid = 1;</code>
     */
    private $userid = 0;
    /**
     *总观看次数,使用pc
     *
     * Generated from protobuf field <code>int32 view_count_pc = 2;</code>
     */
    private $view_count_pc = 0;
    /**
     *总观看次数,使用手机
     *
     * Generated from protobuf field <code>int32 view_count_mobile = 3;</code>
     */
    private $view_count_mobile = 0;
    /**
     *最后一次观看时间
     *
     * Generated from protobuf field <code>string view_time = 4;</code>
     */
    private $view_time = '';

    public function __construct() {
        \GPBMetadata\SchoolWeike::initOnce();
        parent::__construct();
    }

    /**
     *观看者id
     *
     * Generated from protobuf field <code>int64 userid = 1;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     *观看者id
     *
     * Generated from protobuf field <code>int64 userid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     *总观看次数,使用pc
     *
     * Generated from protobuf field <code>int32 view_count_pc = 2;</code>
     * @return int
     */
    public function getViewCountPc()
    {
        return $this->view_count_pc;
    }

    /**
     *总观看次数,使用pc
     *
     * Generated from protobuf field <code>int32 view_count_pc = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setViewCountPc($var)
    {
        GPBUtil::checkInt32($var);
        $this->view_count_pc = $var;

        return $this;
    }

    /**
     *总观看次数,使用手机
     *
     * Generated from protobuf field <code>int32 view_count_mobile = 3;</code>
     * @return int
     */
    public function getViewCountMobile()
    {
        return $this->view_count_mobile;
    }

    /**
     *总观看次数,使用手机
     *
     * Generated from protobuf field <code>int32 view_count_mobile = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setViewCountMobile($var)
    {
        GPBUtil::checkInt32($var);
        $this->view_count_mobile = $var;

        return $this;
    }

    /**
     *最后一次观看时间
     *
     * Generated from protobuf field <code>string view_time = 4;</code>
     * @return string
     */
    public function getViewTime()
    {
        return $this->view_time;
    }

    /**
     *最后一次观看时间
     *
     * Generated from protobuf field <code>string view_time = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setViewTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->view_time = $var;

        return $this;
    }

}

