<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_weike.proto

namespace Cfwf\Micro_service\School_weike;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_weike.ClassWeikeViewCountItem</code>
 */
class ClassWeikeViewCountItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 classid = 1;</code>
     */
    private $classid = 0;
    /**
     * Generated from protobuf field <code>int32 count = 2;</code>
     */
    private $count = 0;

    public function __construct() {
        \GPBMetadata\SchoolWeike::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 classid = 1;</code>
     * @return int|string
     */
    public function getClassid()
    {
        return $this->classid;
    }

    /**
     * Generated from protobuf field <code>int64 classid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClassid($var)
    {
        GPBUtil::checkInt64($var);
        $this->classid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 count = 2;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>int32 count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->count = $var;

        return $this;
    }

}

