<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_weike.proto

namespace Cfwf\Micro_service\School_weike;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_weike.DealWeikeApplyResponse</code>
 */
class DealWeikeApplyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.school_weike.RPC_CALL_RESULT result = 1;</code>
     */
    private $result = 0;
    /**
     *1:操作成功 2：操作失败
     *
     * Generated from protobuf field <code>int32 deal_result = 2;</code>
     */
    private $deal_result = 0;
    /**
     *失败信息	
     *
     * Generated from protobuf field <code>string msg = 3;</code>
     */
    private $msg = '';

    public function __construct() {
        \GPBMetadata\SchoolWeike::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.school_weike.RPC_CALL_RESULT result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.school_weike.RPC_CALL_RESULT result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\School_weike\RPC_CALL_RESULT::class);
        $this->result = $var;

        return $this;
    }

    /**
     *1:操作成功 2：操作失败
     *
     * Generated from protobuf field <code>int32 deal_result = 2;</code>
     * @return int
     */
    public function getDealResult()
    {
        return $this->deal_result;
    }

    /**
     *1:操作成功 2：操作失败
     *
     * Generated from protobuf field <code>int32 deal_result = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDealResult($var)
    {
        GPBUtil::checkInt32($var);
        $this->deal_result = $var;

        return $this;
    }

    /**
     *失败信息	
     *
     * Generated from protobuf field <code>string msg = 3;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     *失败信息	
     *
     * Generated from protobuf field <code>string msg = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

}

