<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_weike.proto

namespace Cfwf\Micro_service\School_weike;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_weike.DeleteWeikeResponse</code>
 */
class DeleteWeikeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.school_weike.RPC_CALL_RESULT result = 1;</code>
     */
    private $result = 0;
    /**
     *1:删除成功 2：删除失败
     *
     * Generated from protobuf field <code>bool delete_result = 2;</code>
     */
    private $delete_result = false;
    /**
     *失败信息	
     *
     * Generated from protobuf field <code>string msg = 3;</code>
     */
    private $msg = '';

    public function __construct() {
        \GPBMetadata\SchoolWeike::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.school_weike.RPC_CALL_RESULT result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.school_weike.RPC_CALL_RESULT result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\School_weike\RPC_CALL_RESULT::class);
        $this->result = $var;

        return $this;
    }

    /**
     *1:删除成功 2：删除失败
     *
     * Generated from protobuf field <code>bool delete_result = 2;</code>
     * @return bool
     */
    public function getDeleteResult()
    {
        return $this->delete_result;
    }

    /**
     *1:删除成功 2：删除失败
     *
     * Generated from protobuf field <code>bool delete_result = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setDeleteResult($var)
    {
        GPBUtil::checkBool($var);
        $this->delete_result = $var;

        return $this;
    }

    /**
     *失败信息	
     *
     * Generated from protobuf field <code>string msg = 3;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     *失败信息	
     *
     * Generated from protobuf field <code>string msg = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

}

