<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_weike.proto

namespace Cfwf\Micro_service\School_weike;

/**
 *微课观看设备类型枚举
 *
 * Protobuf enum <code>Cfwf\Micro_service\School_weike\DEVICE_TYPE</code>
 */
class DEVICE_TYPE
{
    /**
     *使用电脑观看
     *
     * Generated from protobuf enum <code>DEVICE_TYPE_PC = 0;</code>
     */
    const DEVICE_TYPE_PC = 0;
    /**
     *使用手机观看
     *
     * Generated from protobuf enum <code>DEVICE_TYPE_MOBILEPHONE = 1;</code>
     */
    const DEVICE_TYPE_MOBILEPHONE = 1;
}

