<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_weike.proto

namespace Cfwf\Micro_service\School_weike;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_weike.GetApplyListRequest</code>
 */
class GetApplyListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *学校ID
     *
     * Generated from protobuf field <code>int32 schoolid = 1;</code>
     */
    private $schoolid = 0;
    /**
     *年级学科分类
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.school_weike.Grade_and_Subject grade_subject = 2;</code>
     */
    private $grade_subject;
    /**
     *搜索关键字
     *
     * Generated from protobuf field <code>string keyword = 3;</code>
     */
    private $keyword = '';
    /**
     *第几页
     *
     * Generated from protobuf field <code>int32 page = 4;</code>
     */
    private $page = 0;
    /**
     *一页显示多少条
     *
     * Generated from protobuf field <code>int32 pagesize = 5;</code>
     */
    private $pagesize = 0;

    public function __construct() {
        \GPBMetadata\SchoolWeike::initOnce();
        parent::__construct();
    }

    /**
     *学校ID
     *
     * Generated from protobuf field <code>int32 schoolid = 1;</code>
     * @return int
     */
    public function getSchoolid()
    {
        return $this->schoolid;
    }

    /**
     *学校ID
     *
     * Generated from protobuf field <code>int32 schoolid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSchoolid($var)
    {
        GPBUtil::checkInt32($var);
        $this->schoolid = $var;

        return $this;
    }

    /**
     *年级学科分类
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.school_weike.Grade_and_Subject grade_subject = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGradeSubject()
    {
        return $this->grade_subject;
    }

    /**
     *年级学科分类
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.school_weike.Grade_and_Subject grade_subject = 2;</code>
     * @param \Cfwf\Micro_service\School_weike\Grade_and_Subject[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGradeSubject($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cfwf\Micro_service\School_weike\Grade_and_Subject::class);
        $this->grade_subject = $arr;

        return $this;
    }

    /**
     *搜索关键字
     *
     * Generated from protobuf field <code>string keyword = 3;</code>
     * @return string
     */
    public function getKeyword()
    {
        return $this->keyword;
    }

    /**
     *搜索关键字
     *
     * Generated from protobuf field <code>string keyword = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyword($var)
    {
        GPBUtil::checkString($var, True);
        $this->keyword = $var;

        return $this;
    }

    /**
     *第几页
     *
     * Generated from protobuf field <code>int32 page = 4;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     *第几页
     *
     * Generated from protobuf field <code>int32 page = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     *一页显示多少条
     *
     * Generated from protobuf field <code>int32 pagesize = 5;</code>
     * @return int
     */
    public function getPagesize()
    {
        return $this->pagesize;
    }

    /**
     *一页显示多少条
     *
     * Generated from protobuf field <code>int32 pagesize = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPagesize($var)
    {
        GPBUtil::checkInt32($var);
        $this->pagesize = $var;

        return $this;
    }

}

