<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_weike.proto

namespace Cfwf\Micro_service\School_weike;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *获取某个微课在哪些班级发布了
 *
 * Generated from protobuf message <code>cfwf.micro_service.school_weike.GetClassidRequest</code>
 */
class GetClassidRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *班级id
     *
     * Generated from protobuf field <code>int64 weike_id = 1;</code>
     */
    private $weike_id = 0;

    public function __construct() {
        \GPBMetadata\SchoolWeike::initOnce();
        parent::__construct();
    }

    /**
     *班级id
     *
     * Generated from protobuf field <code>int64 weike_id = 1;</code>
     * @return int|string
     */
    public function getWeikeId()
    {
        return $this->weike_id;
    }

    /**
     *班级id
     *
     * Generated from protobuf field <code>int64 weike_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWeikeId($var)
    {
        GPBUtil::checkInt64($var);
        $this->weike_id = $var;

        return $this;
    }

}

