<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_weike.proto

namespace Cfwf\Micro_service\School_weike;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_weike.GetWeikeListRequest</code>
 */
class GetWeikeListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *第几页
     *
     * Generated from protobuf field <code>int32 page = 1;</code>
     */
    private $page = 0;
    /**
     *一页显示多少条
     *
     * Generated from protobuf field <code>int32 pagesize = 2;</code>
     */
    private $pagesize = 0;
    /**
     *发布者ID
     *
     * Generated from protobuf field <code>int64 userid = 3;</code>
     */
    private $userid = 0;
    /**
     *学校ID
     *
     * Generated from protobuf field <code>int32 schoolid = 4;</code>
     */
    private $schoolid = 0;
    /**
     *视频公开方式 0=所有（公开+本校） 1=本校 2=公开
     *
     * Generated from protobuf field <code>int32 view_type = 5;</code>
     */
    private $view_type = 0;
    /**
     *市/区县ID
     *
     * Generated from protobuf field <code>int32 cityid = 6;</code>
     */
    private $cityid = 0;
    /**
     *开始时间 '2017-08-08 12:03:00'
     *
     * Generated from protobuf field <code>string start_time = 7;</code>
     */
    private $start_time = '';
    /**
     *结束时间 '2017-08-08 12:03:00'
     *
     * Generated from protobuf field <code>string end_time = 8;</code>
     */
    private $end_time = '';
    /**
     *年级学科分类
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.school_weike.Grade_and_Subject grade_subject = 9;</code>
     */
    private $grade_subject;
    /**
     *搜索关键字
     *
     * Generated from protobuf field <code>string keyword = 10;</code>
     */
    private $keyword = '';
    /**
     *排序方式 1-最新发布 2-点击最多
     *
     * Generated from protobuf field <code>int32 order = 11;</code>
     */
    private $order = 0;
    /**
     *章节ID 
     *
     * Generated from protobuf field <code>int32 chapterid = 12;</code>
     */
    private $chapterid = 0;
    /**
     *可以传入多个id，id之间用‘,’分隔
     *
     * Generated from protobuf field <code>string cityid_list = 13;</code>
     */
    private $cityid_list = '';

    public function __construct() {
        \GPBMetadata\SchoolWeike::initOnce();
        parent::__construct();
    }

    /**
     *第几页
     *
     * Generated from protobuf field <code>int32 page = 1;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     *第几页
     *
     * Generated from protobuf field <code>int32 page = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     *一页显示多少条
     *
     * Generated from protobuf field <code>int32 pagesize = 2;</code>
     * @return int
     */
    public function getPagesize()
    {
        return $this->pagesize;
    }

    /**
     *一页显示多少条
     *
     * Generated from protobuf field <code>int32 pagesize = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPagesize($var)
    {
        GPBUtil::checkInt32($var);
        $this->pagesize = $var;

        return $this;
    }

    /**
     *发布者ID
     *
     * Generated from protobuf field <code>int64 userid = 3;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     *发布者ID
     *
     * Generated from protobuf field <code>int64 userid = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     *学校ID
     *
     * Generated from protobuf field <code>int32 schoolid = 4;</code>
     * @return int
     */
    public function getSchoolid()
    {
        return $this->schoolid;
    }

    /**
     *学校ID
     *
     * Generated from protobuf field <code>int32 schoolid = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSchoolid($var)
    {
        GPBUtil::checkInt32($var);
        $this->schoolid = $var;

        return $this;
    }

    /**
     *视频公开方式 0=所有（公开+本校） 1=本校 2=公开
     *
     * Generated from protobuf field <code>int32 view_type = 5;</code>
     * @return int
     */
    public function getViewType()
    {
        return $this->view_type;
    }

    /**
     *视频公开方式 0=所有（公开+本校） 1=本校 2=公开
     *
     * Generated from protobuf field <code>int32 view_type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setViewType($var)
    {
        GPBUtil::checkInt32($var);
        $this->view_type = $var;

        return $this;
    }

    /**
     *市/区县ID
     *
     * Generated from protobuf field <code>int32 cityid = 6;</code>
     * @return int
     */
    public function getCityid()
    {
        return $this->cityid;
    }

    /**
     *市/区县ID
     *
     * Generated from protobuf field <code>int32 cityid = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCityid($var)
    {
        GPBUtil::checkInt32($var);
        $this->cityid = $var;

        return $this;
    }

    /**
     *开始时间 '2017-08-08 12:03:00'
     *
     * Generated from protobuf field <code>string start_time = 7;</code>
     * @return string
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     *开始时间 '2017-08-08 12:03:00'
     *
     * Generated from protobuf field <code>string start_time = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_time = $var;

        return $this;
    }

    /**
     *结束时间 '2017-08-08 12:03:00'
     *
     * Generated from protobuf field <code>string end_time = 8;</code>
     * @return string
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    /**
     *结束时间 '2017-08-08 12:03:00'
     *
     * Generated from protobuf field <code>string end_time = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->end_time = $var;

        return $this;
    }

    /**
     *年级学科分类
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.school_weike.Grade_and_Subject grade_subject = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGradeSubject()
    {
        return $this->grade_subject;
    }

    /**
     *年级学科分类
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.school_weike.Grade_and_Subject grade_subject = 9;</code>
     * @param \Cfwf\Micro_service\School_weike\Grade_and_Subject[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGradeSubject($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cfwf\Micro_service\School_weike\Grade_and_Subject::class);
        $this->grade_subject = $arr;

        return $this;
    }

    /**
     *搜索关键字
     *
     * Generated from protobuf field <code>string keyword = 10;</code>
     * @return string
     */
    public function getKeyword()
    {
        return $this->keyword;
    }

    /**
     *搜索关键字
     *
     * Generated from protobuf field <code>string keyword = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyword($var)
    {
        GPBUtil::checkString($var, True);
        $this->keyword = $var;

        return $this;
    }

    /**
     *排序方式 1-最新发布 2-点击最多
     *
     * Generated from protobuf field <code>int32 order = 11;</code>
     * @return int
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     *排序方式 1-最新发布 2-点击最多
     *
     * Generated from protobuf field <code>int32 order = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setOrder($var)
    {
        GPBUtil::checkInt32($var);
        $this->order = $var;

        return $this;
    }

    /**
     *章节ID 
     *
     * Generated from protobuf field <code>int32 chapterid = 12;</code>
     * @return int
     */
    public function getChapterid()
    {
        return $this->chapterid;
    }

    /**
     *章节ID 
     *
     * Generated from protobuf field <code>int32 chapterid = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setChapterid($var)
    {
        GPBUtil::checkInt32($var);
        $this->chapterid = $var;

        return $this;
    }

    /**
     *可以传入多个id，id之间用‘,’分隔
     *
     * Generated from protobuf field <code>string cityid_list = 13;</code>
     * @return string
     */
    public function getCityidList()
    {
        return $this->cityid_list;
    }

    /**
     *可以传入多个id，id之间用‘,’分隔
     *
     * Generated from protobuf field <code>string cityid_list = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setCityidList($var)
    {
        GPBUtil::checkString($var, True);
        $this->cityid_list = $var;

        return $this;
    }

}

