<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_weike.proto

namespace Cfwf\Micro_service\School_weike;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_weike.Grade_and_Subject</code>
 */
class Grade_and_Subject extends \Google\Protobuf\Internal\Message
{
    /**
     *学科
     *
     * Generated from protobuf field <code>int32 grade = 1;</code>
     */
    private $grade = 0;
    /**
     *科目（如果有多个，就用‘,’作为分隔符）
     *
     * Generated from protobuf field <code>string subject = 2;</code>
     */
    private $subject = '';

    public function __construct() {
        \GPBMetadata\SchoolWeike::initOnce();
        parent::__construct();
    }

    /**
     *学科
     *
     * Generated from protobuf field <code>int32 grade = 1;</code>
     * @return int
     */
    public function getGrade()
    {
        return $this->grade;
    }

    /**
     *学科
     *
     * Generated from protobuf field <code>int32 grade = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setGrade($var)
    {
        GPBUtil::checkInt32($var);
        $this->grade = $var;

        return $this;
    }

    /**
     *科目（如果有多个，就用‘,’作为分隔符）
     *
     * Generated from protobuf field <code>string subject = 2;</code>
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     *科目（如果有多个，就用‘,’作为分隔符）
     *
     * Generated from protobuf field <code>string subject = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject = $var;

        return $this;
    }

}

