<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_weike.proto

namespace Cfwf\Micro_service\School_weike;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_weike.ViewWeikeByClassStudentRequest</code>
 */
class ViewWeikeByClassStudentRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *微课ID
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    private $id = 0;
    /**
     *观看者ID
     *
     * Generated from protobuf field <code>int64 userid = 2;</code>
     */
    private $userid = 0;
    /**
     *使用何种设备观看
     *
     * Generated from protobuf field <code>.cfwf.micro_service.school_weike.DEVICE_TYPE device = 3;</code>
     */
    private $device = 0;
    /**
     *班级ID
     *
     * Generated from protobuf field <code>int32 classid = 4;</code>
     */
    private $classid = 0;

    public function __construct() {
        \GPBMetadata\SchoolWeike::initOnce();
        parent::__construct();
    }

    /**
     *微课ID
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     *微课ID
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     *观看者ID
     *
     * Generated from protobuf field <code>int64 userid = 2;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     *观看者ID
     *
     * Generated from protobuf field <code>int64 userid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     *使用何种设备观看
     *
     * Generated from protobuf field <code>.cfwf.micro_service.school_weike.DEVICE_TYPE device = 3;</code>
     * @return int
     */
    public function getDevice()
    {
        return $this->device;
    }

    /**
     *使用何种设备观看
     *
     * Generated from protobuf field <code>.cfwf.micro_service.school_weike.DEVICE_TYPE device = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setDevice($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\School_weike\DEVICE_TYPE::class);
        $this->device = $var;

        return $this;
    }

    /**
     *班级ID
     *
     * Generated from protobuf field <code>int32 classid = 4;</code>
     * @return int
     */
    public function getClassid()
    {
        return $this->classid;
    }

    /**
     *班级ID
     *
     * Generated from protobuf field <code>int32 classid = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setClassid($var)
    {
        GPBUtil::checkInt32($var);
        $this->classid = $var;

        return $this;
    }

}

