<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_weike.proto

namespace Cfwf\Micro_service\School_weike;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_weike.WeikeItem</code>
 */
class WeikeItem extends \Google\Protobuf\Internal\Message
{
    /**
     *微课标题
     *
     * Generated from protobuf field <code>string title = 1;</code>
     */
    private $title = '';
    /**
     *微课ID
     *
     * Generated from protobuf field <code>int64 weike_id = 2;</code>
     */
    private $weike_id = 0;
    /**
     *发布者ID	 
     *
     * Generated from protobuf field <code>int64 userid = 3;</code>
     */
    private $userid = 0;
    /**
     *微课观看次数
     *
     * Generated from protobuf field <code>int32 view_count = 4;</code>
     */
    private $view_count = 0;
    /**
     *封面资源id	
     *
     * Generated from protobuf field <code>string cover_resid = 5;</code>
     */
    private $cover_resid = '';
    /**
     *发布时间
     *
     * Generated from protobuf field <code>string public_time = 6;</code>
     */
    private $public_time = '';
    /**
     *视频公开方式 0=所有 1=本校 2=公开
     *
     * Generated from protobuf field <code>int32 view_type = 7;</code>
     */
    private $view_type = 0;
    /**
     *视频资源id
     *
     * Generated from protobuf field <code>string file_resid = 8;</code>
     */
    private $file_resid = '';
    /**
     *学校ID
     *
     * Generated from protobuf field <code>int64 schoolid = 9;</code>
     */
    private $schoolid = 0;
    /**
     *课程描述
     *
     * Generated from protobuf field <code>string description = 10;</code>
     */
    private $description = '';
    /**
     *视频时长
     *
     * Generated from protobuf field <code>int32 duiation = 11;</code>
     */
    private $duiation = 0;
    /**
     *年级
     *
     * Generated from protobuf field <code>int32 grade = 12;</code>
     */
    private $grade = 0;
    /**
     *学科
     *
     * Generated from protobuf field <code>int32 subject = 13;</code>
     */
    private $subject = 0;
    /**
     *点赞量	
     *
     * Generated from protobuf field <code>int32 dianzhan = 14;</code>
     */
    private $dianzhan = 0;
    /**
     *生效时间
     *
     * Generated from protobuf field <code>string effect_time = 15;</code>
     */
    private $effect_time = '';

    public function __construct() {
        \GPBMetadata\SchoolWeike::initOnce();
        parent::__construct();
    }

    /**
     *微课标题
     *
     * Generated from protobuf field <code>string title = 1;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     *微课标题
     *
     * Generated from protobuf field <code>string title = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     *微课ID
     *
     * Generated from protobuf field <code>int64 weike_id = 2;</code>
     * @return int|string
     */
    public function getWeikeId()
    {
        return $this->weike_id;
    }

    /**
     *微课ID
     *
     * Generated from protobuf field <code>int64 weike_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWeikeId($var)
    {
        GPBUtil::checkInt64($var);
        $this->weike_id = $var;

        return $this;
    }

    /**
     *发布者ID	 
     *
     * Generated from protobuf field <code>int64 userid = 3;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     *发布者ID	 
     *
     * Generated from protobuf field <code>int64 userid = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     *微课观看次数
     *
     * Generated from protobuf field <code>int32 view_count = 4;</code>
     * @return int
     */
    public function getViewCount()
    {
        return $this->view_count;
    }

    /**
     *微课观看次数
     *
     * Generated from protobuf field <code>int32 view_count = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setViewCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->view_count = $var;

        return $this;
    }

    /**
     *封面资源id	
     *
     * Generated from protobuf field <code>string cover_resid = 5;</code>
     * @return string
     */
    public function getCoverResid()
    {
        return $this->cover_resid;
    }

    /**
     *封面资源id	
     *
     * Generated from protobuf field <code>string cover_resid = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCoverResid($var)
    {
        GPBUtil::checkString($var, True);
        $this->cover_resid = $var;

        return $this;
    }

    /**
     *发布时间
     *
     * Generated from protobuf field <code>string public_time = 6;</code>
     * @return string
     */
    public function getPublicTime()
    {
        return $this->public_time;
    }

    /**
     *发布时间
     *
     * Generated from protobuf field <code>string public_time = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPublicTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->public_time = $var;

        return $this;
    }

    /**
     *视频公开方式 0=所有 1=本校 2=公开
     *
     * Generated from protobuf field <code>int32 view_type = 7;</code>
     * @return int
     */
    public function getViewType()
    {
        return $this->view_type;
    }

    /**
     *视频公开方式 0=所有 1=本校 2=公开
     *
     * Generated from protobuf field <code>int32 view_type = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setViewType($var)
    {
        GPBUtil::checkInt32($var);
        $this->view_type = $var;

        return $this;
    }

    /**
     *视频资源id
     *
     * Generated from protobuf field <code>string file_resid = 8;</code>
     * @return string
     */
    public function getFileResid()
    {
        return $this->file_resid;
    }

    /**
     *视频资源id
     *
     * Generated from protobuf field <code>string file_resid = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setFileResid($var)
    {
        GPBUtil::checkString($var, True);
        $this->file_resid = $var;

        return $this;
    }

    /**
     *学校ID
     *
     * Generated from protobuf field <code>int64 schoolid = 9;</code>
     * @return int|string
     */
    public function getSchoolid()
    {
        return $this->schoolid;
    }

    /**
     *学校ID
     *
     * Generated from protobuf field <code>int64 schoolid = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSchoolid($var)
    {
        GPBUtil::checkInt64($var);
        $this->schoolid = $var;

        return $this;
    }

    /**
     *课程描述
     *
     * Generated from protobuf field <code>string description = 10;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     *课程描述
     *
     * Generated from protobuf field <code>string description = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     *视频时长
     *
     * Generated from protobuf field <code>int32 duiation = 11;</code>
     * @return int
     */
    public function getDuiation()
    {
        return $this->duiation;
    }

    /**
     *视频时长
     *
     * Generated from protobuf field <code>int32 duiation = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setDuiation($var)
    {
        GPBUtil::checkInt32($var);
        $this->duiation = $var;

        return $this;
    }

    /**
     *年级
     *
     * Generated from protobuf field <code>int32 grade = 12;</code>
     * @return int
     */
    public function getGrade()
    {
        return $this->grade;
    }

    /**
     *年级
     *
     * Generated from protobuf field <code>int32 grade = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setGrade($var)
    {
        GPBUtil::checkInt32($var);
        $this->grade = $var;

        return $this;
    }

    /**
     *学科
     *
     * Generated from protobuf field <code>int32 subject = 13;</code>
     * @return int
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     *学科
     *
     * Generated from protobuf field <code>int32 subject = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkInt32($var);
        $this->subject = $var;

        return $this;
    }

    /**
     *点赞量	
     *
     * Generated from protobuf field <code>int32 dianzhan = 14;</code>
     * @return int
     */
    public function getDianzhan()
    {
        return $this->dianzhan;
    }

    /**
     *点赞量	
     *
     * Generated from protobuf field <code>int32 dianzhan = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setDianzhan($var)
    {
        GPBUtil::checkInt32($var);
        $this->dianzhan = $var;

        return $this;
    }

    /**
     *生效时间
     *
     * Generated from protobuf field <code>string effect_time = 15;</code>
     * @return string
     */
    public function getEffectTime()
    {
        return $this->effect_time;
    }

    /**
     *生效时间
     *
     * Generated from protobuf field <code>string effect_time = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setEffectTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->effect_time = $var;

        return $this;
    }

}

