<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_course_video.proto

namespace Cfwf\Micro_service\School_coursevideo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_coursevideo.Course_delete_status</code>
 */
class Course_delete_status extends \Google\Protobuf\Internal\Message
{
    /**
     *是否被发布者自己删除
     *
     * Generated from protobuf field <code>bool is_delete_by_self = 1;</code>
     */
    private $is_delete_by_self = false;
    /**
     *是否被学校管理员删除
     *
     * Generated from protobuf field <code>bool is_delete_by_school = 2;</code>
     */
    private $is_delete_by_school = false;
    /**
     *是否被区县管理员删除
     *
     * Generated from protobuf field <code>bool is_delete_by_country = 3;</code>
     */
    private $is_delete_by_country = false;
    /**
     *是否被市管理员删除
     *
     * Generated from protobuf field <code>bool is_delete_by_city = 4;</code>
     */
    private $is_delete_by_city = false;
    /**
     *是否被系统管理员删除
     *
     * Generated from protobuf field <code>bool is_delete_by_sysadmin = 5;</code>
     */
    private $is_delete_by_sysadmin = false;

    public function __construct() {
        \GPBMetadata\SchoolCourseVideo::initOnce();
        parent::__construct();
    }

    /**
     *是否被发布者自己删除
     *
     * Generated from protobuf field <code>bool is_delete_by_self = 1;</code>
     * @return bool
     */
    public function getIsDeleteBySelf()
    {
        return $this->is_delete_by_self;
    }

    /**
     *是否被发布者自己删除
     *
     * Generated from protobuf field <code>bool is_delete_by_self = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDeleteBySelf($var)
    {
        GPBUtil::checkBool($var);
        $this->is_delete_by_self = $var;

        return $this;
    }

    /**
     *是否被学校管理员删除
     *
     * Generated from protobuf field <code>bool is_delete_by_school = 2;</code>
     * @return bool
     */
    public function getIsDeleteBySchool()
    {
        return $this->is_delete_by_school;
    }

    /**
     *是否被学校管理员删除
     *
     * Generated from protobuf field <code>bool is_delete_by_school = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDeleteBySchool($var)
    {
        GPBUtil::checkBool($var);
        $this->is_delete_by_school = $var;

        return $this;
    }

    /**
     *是否被区县管理员删除
     *
     * Generated from protobuf field <code>bool is_delete_by_country = 3;</code>
     * @return bool
     */
    public function getIsDeleteByCountry()
    {
        return $this->is_delete_by_country;
    }

    /**
     *是否被区县管理员删除
     *
     * Generated from protobuf field <code>bool is_delete_by_country = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDeleteByCountry($var)
    {
        GPBUtil::checkBool($var);
        $this->is_delete_by_country = $var;

        return $this;
    }

    /**
     *是否被市管理员删除
     *
     * Generated from protobuf field <code>bool is_delete_by_city = 4;</code>
     * @return bool
     */
    public function getIsDeleteByCity()
    {
        return $this->is_delete_by_city;
    }

    /**
     *是否被市管理员删除
     *
     * Generated from protobuf field <code>bool is_delete_by_city = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDeleteByCity($var)
    {
        GPBUtil::checkBool($var);
        $this->is_delete_by_city = $var;

        return $this;
    }

    /**
     *是否被系统管理员删除
     *
     * Generated from protobuf field <code>bool is_delete_by_sysadmin = 5;</code>
     * @return bool
     */
    public function getIsDeleteBySysadmin()
    {
        return $this->is_delete_by_sysadmin;
    }

    /**
     *是否被系统管理员删除
     *
     * Generated from protobuf field <code>bool is_delete_by_sysadmin = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDeleteBySysadmin($var)
    {
        GPBUtil::checkBool($var);
        $this->is_delete_by_sysadmin = $var;

        return $this;
    }

}

