<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_course_video.proto

namespace Cfwf\Micro_service\School_coursevideo;

/**
 *视频审核状态
 *
 * Protobuf enum <code>Cfwf\Micro_service\School_coursevideo\COURSEVIDEO_APPROVE_STATUS</code>
 */
class COURSEVIDEO_APPROVE_STATUS
{
    /**
     * Generated from protobuf enum <code>COURSEVIDEO_APPROVE_STATUS_INIT = 0;</code>
     */
    const COURSEVIDEO_APPROVE_STATUS_INIT = 0;
    /**
     *等待审核中
     *
     * Generated from protobuf enum <code>COURSEVIDEO_APPROVE_STATUS_WAIT = 1;</code>
     */
    const COURSEVIDEO_APPROVE_STATUS_WAIT = 1;
    /**
     *审核通过
     *
     * Generated from protobuf enum <code>COURSEVIDEO_APPROVE_STATUS_ACCEPT = 2;</code>
     */
    const COURSEVIDEO_APPROVE_STATUS_ACCEPT = 2;
    /**
     *审核未通过
     *
     * Generated from protobuf enum <code>COURSEVIDEO_APPROVE_STATUS_REFUSE = 3;</code>
     */
    const COURSEVIDEO_APPROVE_STATUS_REFUSE = 3;
}

