<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_course_video.proto

namespace Cfwf\Micro_service\School_coursevideo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_coursevideo.DeleteCourseVideoResponse</code>
 */
class DeleteCourseVideoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.school_coursevideo.RPC_CALL_RESULT result = 1;</code>
     */
    private $result = 0;
    /**
     *失败信息	  
     *
     * Generated from protobuf field <code>string msg = 2;</code>
     */
    private $msg = '';
    /**
     * Generated from protobuf field <code>repeated .cfwf.micro_service.school_coursevideo.CourseVideoItem list = 3;</code>
     */
    private $list;

    public function __construct() {
        \GPBMetadata\SchoolCourseVideo::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.school_coursevideo.RPC_CALL_RESULT result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.school_coursevideo.RPC_CALL_RESULT result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\School_coursevideo\RPC_CALL_RESULT::class);
        $this->result = $var;

        return $this;
    }

    /**
     *失败信息	  
     *
     * Generated from protobuf field <code>string msg = 2;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     *失败信息	  
     *
     * Generated from protobuf field <code>string msg = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cfwf.micro_service.school_coursevideo.CourseVideoItem list = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getList()
    {
        return $this->list;
    }

    /**
     * Generated from protobuf field <code>repeated .cfwf.micro_service.school_coursevideo.CourseVideoItem list = 3;</code>
     * @param \Cfwf\Micro_service\School_coursevideo\CourseVideoItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cfwf\Micro_service\School_coursevideo\CourseVideoItem::class);
        $this->list = $arr;

        return $this;
    }

}

