<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_course_video.proto

namespace Cfwf\Micro_service\School_coursevideo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_coursevideo.DeleteCourseVideoRequest</code>
 */
class DeleteCourseVideoRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *课程ID
     *
     * Generated from protobuf field <code>repeated string id = 1;</code>
     */
    private $id;
    /**
     *用户类型
     *
     * Generated from protobuf field <code>.cfwf.micro_service.school_coursevideo.DELETE_COURSEVIDEO_USER_TYPE user_type = 2;</code>
     */
    private $user_type = 0;
    /**
     *操作者ID
     *
     * Generated from protobuf field <code>int64 userid = 3;</code>
     */
    private $userid = 0;

    public function __construct() {
        \GPBMetadata\SchoolCourseVideo::initOnce();
        parent::__construct();
    }

    /**
     *课程ID
     *
     * Generated from protobuf field <code>repeated string id = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     *课程ID
     *
     * Generated from protobuf field <code>repeated string id = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->id = $arr;

        return $this;
    }

    /**
     *用户类型
     *
     * Generated from protobuf field <code>.cfwf.micro_service.school_coursevideo.DELETE_COURSEVIDEO_USER_TYPE user_type = 2;</code>
     * @return int
     */
    public function getUserType()
    {
        return $this->user_type;
    }

    /**
     *用户类型
     *
     * Generated from protobuf field <code>.cfwf.micro_service.school_coursevideo.DELETE_COURSEVIDEO_USER_TYPE user_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUserType($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\School_coursevideo\DELETE_COURSEVIDEO_USER_TYPE::class);
        $this->user_type = $var;

        return $this;
    }

    /**
     *操作者ID
     *
     * Generated from protobuf field <code>int64 userid = 3;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     *操作者ID
     *
     * Generated from protobuf field <code>int64 userid = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->userid = $var;

        return $this;
    }

}

