<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_course_video.proto

namespace Cfwf\Micro_service\School_coursevideo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_coursevideo.GetCourseVideoInfoResponse</code>
 */
class GetCourseVideoInfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.school_coursevideo.RPC_CALL_RESULT result = 1;</code>
     */
    private $result = 0;
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.school_coursevideo.CourseVideoItem item = 2;</code>
     */
    private $item = null;

    public function __construct() {
        \GPBMetadata\SchoolCourseVideo::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.school_coursevideo.RPC_CALL_RESULT result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.school_coursevideo.RPC_CALL_RESULT result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\School_coursevideo\RPC_CALL_RESULT::class);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.school_coursevideo.CourseVideoItem item = 2;</code>
     * @return \Cfwf\Micro_service\School_coursevideo\CourseVideoItem
     */
    public function getItem()
    {
        return $this->item;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.school_coursevideo.CourseVideoItem item = 2;</code>
     * @param \Cfwf\Micro_service\School_coursevideo\CourseVideoItem $var
     * @return $this
     */
    public function setItem($var)
    {
        GPBUtil::checkMessage($var, \Cfwf\Micro_service\School_coursevideo\CourseVideoItem::class);
        $this->item = $var;

        return $this;
    }

}

