<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_course_video.proto

namespace Cfwf\Micro_service\School_coursevideo;

/**
 *查询者类型
 *
 * Protobuf enum <code>Cfwf\Micro_service\School_coursevideo\SEARCH_TYPE</code>
 */
class SEARCH_TYPE
{
    /**
     * Generated from protobuf enum <code>SEARCH_TYPE_INIT = 0;</code>
     */
    const SEARCH_TYPE_INIT = 0;
    /**
     *发布者自己查询
     *
     * Generated from protobuf enum <code>SEARCH_TYPE_SELE = 1;</code>
     */
    const SEARCH_TYPE_SELE = 1;
    /**
     *学校查询
     *
     * Generated from protobuf enum <code>SEARCH_TYPE_SCHOOL = 2;</code>
     */
    const SEARCH_TYPE_SCHOOL = 2;
    /**
     *区县查询
     *
     * Generated from protobuf enum <code>SEARCH_TYPE_COUNTYR = 3;</code>
     */
    const SEARCH_TYPE_COUNTYR = 3;
    /**
     *市查询
     *
     * Generated from protobuf enum <code>SEARCH_TYPE_CITY = 4;</code>
     */
    const SEARCH_TYPE_CITY = 4;
}

