<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_course_video.proto

namespace Cfwf\Micro_service\School_coursevideo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *观看课堂实录，增加观看数
 *
 * Generated from protobuf message <code>cfwf.micro_service.school_coursevideo.ViewCourseVideoRequest</code>
 */
class ViewCourseVideoRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *课程id
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    private $id = 0;

    public function __construct() {
        \GPBMetadata\SchoolCourseVideo::initOnce();
        parent::__construct();
    }

    /**
     *课程id
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     *课程id
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

}

