<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_course_video.proto

namespace Cfwf\Micro_service\School_coursevideo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_coursevideo.ViewCourseVideoRequest</code>
 */
class ViewCourseVideoRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *课程id
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    private $id = 0;
    /**
     *观看者ID
     *
     * Generated from protobuf field <code>int64 userid = 2;</code>
     */
    private $userid = 0;
    /**
     *使用何种设备观看
     *
     * Generated from protobuf field <code>.cfwf.micro_service.school_coursevideo.DEVICE_TYPE device = 3;</code>
     */
    private $device = 0;
    /**
     *观看者ip
     *
     * Generated from protobuf field <code>string client_ip = 4;</code>
     */
    private $client_ip = '';

    public function __construct() {
        \GPBMetadata\SchoolCourseVideo::initOnce();
        parent::__construct();
    }

    /**
     *课程id
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     *课程id
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     *观看者ID
     *
     * Generated from protobuf field <code>int64 userid = 2;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     *观看者ID
     *
     * Generated from protobuf field <code>int64 userid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     *使用何种设备观看
     *
     * Generated from protobuf field <code>.cfwf.micro_service.school_coursevideo.DEVICE_TYPE device = 3;</code>
     * @return int
     */
    public function getDevice()
    {
        return $this->device;
    }

    /**
     *使用何种设备观看
     *
     * Generated from protobuf field <code>.cfwf.micro_service.school_coursevideo.DEVICE_TYPE device = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setDevice($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\School_coursevideo\DEVICE_TYPE::class);
        $this->device = $var;

        return $this;
    }

    /**
     *观看者ip
     *
     * Generated from protobuf field <code>string client_ip = 4;</code>
     * @return string
     */
    public function getClientIp()
    {
        return $this->client_ip;
    }

    /**
     *观看者ip
     *
     * Generated from protobuf field <code>string client_ip = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setClientIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_ip = $var;

        return $this;
    }

}

