<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Cfwf\Micro_service\Account;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.account.GetMyBaseInfoResponse</code>
 */
class GetMyBaseInfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.account.RPC_CALL_RESULT result = 1;</code>
     */
    private $result = 0;
    /**
     *基本信息
     *
     * Generated from protobuf field <code>.cfwf.micro_service.account.UserBaseInfo baseinfo = 2;</code>
     */
    private $baseinfo = null;
    /**
     * Generated from protobuf field <code>string email = 3;</code>
     */
    private $email = '';
    /**
     *偏好设置
     *
     * Generated from protobuf field <code>.cfwf.micro_service.account.FREIND_CHECK_TYPE friend_check = 4;</code>
     */
    private $friend_check = 0;

    public function __construct() {
        \GPBMetadata\Account::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.account.RPC_CALL_RESULT result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.account.RPC_CALL_RESULT result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\Account\RPC_CALL_RESULT::class);
        $this->result = $var;

        return $this;
    }

    /**
     *基本信息
     *
     * Generated from protobuf field <code>.cfwf.micro_service.account.UserBaseInfo baseinfo = 2;</code>
     * @return \Cfwf\Micro_service\Account\UserBaseInfo
     */
    public function getBaseinfo()
    {
        return $this->baseinfo;
    }

    /**
     *基本信息
     *
     * Generated from protobuf field <code>.cfwf.micro_service.account.UserBaseInfo baseinfo = 2;</code>
     * @param \Cfwf\Micro_service\Account\UserBaseInfo $var
     * @return $this
     */
    public function setBaseinfo($var)
    {
        GPBUtil::checkMessage($var, \Cfwf\Micro_service\Account\UserBaseInfo::class);
        $this->baseinfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 3;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     *偏好设置
     *
     * Generated from protobuf field <code>.cfwf.micro_service.account.FREIND_CHECK_TYPE friend_check = 4;</code>
     * @return int
     */
    public function getFriendCheck()
    {
        return $this->friend_check;
    }

    /**
     *偏好设置
     *
     * Generated from protobuf field <code>.cfwf.micro_service.account.FREIND_CHECK_TYPE friend_check = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setFriendCheck($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\Account\FREIND_CHECK_TYPE::class);
        $this->friend_check = $var;

        return $this;
    }

}

