<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Cfwf\Micro_service\Account;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.account.GetUserIdResponse</code>
 */
class GetUserIdResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.account.RPC_CALL_RESULT result = 1;</code>
     */
    private $result = 0;
    /**
     * Generated from protobuf field <code>uint64 userid = 2;</code>
     */
    private $userid = 0;
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.account.UserIdentity identity = 3;</code>
     */
    private $identity = null;
    /**
     *如果GetUserIdRequest.loginid传入的是手机号，一个手机号有可能绑定多个userid。此处返回所有绑定该手机号的帐号，其第一条等于GetUserIdResponse.userid。保留userid是要兼容之前版本
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.account.UserAndIdentity users = 4;</code>
     */
    private $users;

    public function __construct() {
        \GPBMetadata\Account::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.account.RPC_CALL_RESULT result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.account.RPC_CALL_RESULT result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\Account\RPC_CALL_RESULT::class);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 userid = 2;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     * Generated from protobuf field <code>uint64 userid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkUint64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.account.UserIdentity identity = 3;</code>
     * @return \Cfwf\Micro_service\Account\UserIdentity
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.account.UserIdentity identity = 3;</code>
     * @param \Cfwf\Micro_service\Account\UserIdentity $var
     * @return $this
     */
    public function setIdentity($var)
    {
        GPBUtil::checkMessage($var, \Cfwf\Micro_service\Account\UserIdentity::class);
        $this->identity = $var;

        return $this;
    }

    /**
     *如果GetUserIdRequest.loginid传入的是手机号，一个手机号有可能绑定多个userid。此处返回所有绑定该手机号的帐号，其第一条等于GetUserIdResponse.userid。保留userid是要兼容之前版本
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.account.UserAndIdentity users = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     *如果GetUserIdRequest.loginid传入的是手机号，一个手机号有可能绑定多个userid。此处返回所有绑定该手机号的帐号，其第一条等于GetUserIdResponse.userid。保留userid是要兼容之前版本
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.account.UserAndIdentity users = 4;</code>
     * @param \Cfwf\Micro_service\Account\UserAndIdentity[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUsers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cfwf\Micro_service\Account\UserAndIdentity::class);
        $this->users = $arr;

        return $this;
    }

}

