<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Cfwf\Micro_service\Account;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.account.GetUserIdRequest</code>
 */
class GetUserIdRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *loginid，手机号
     *
     * Generated from protobuf field <code>string loginid = 1;</code>
     */
    private $loginid = '';

    public function __construct() {
        \GPBMetadata\Account::initOnce();
        parent::__construct();
    }

    /**
     *loginid，手机号
     *
     * Generated from protobuf field <code>string loginid = 1;</code>
     * @return string
     */
    public function getLoginid()
    {
        return $this->loginid;
    }

    /**
     *loginid，手机号
     *
     * Generated from protobuf field <code>string loginid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLoginid($var)
    {
        GPBUtil::checkString($var, True);
        $this->loginid = $var;

        return $this;
    }

}

