<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Cfwf\Micro_service\Account;

use Google\Protobuf\Internal\GPBUtil;

/**
 *注册，可指定账号
 *
 * Generated from protobuf message <code>cfwf.micro_service.account.RegistNewAccountRequest</code>
 */
class RegistNewAccountRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *可填可不填
     *
     * Generated from protobuf field <code>string cb_id = 1;</code>
     */
    private $cb_id = '';
    /**
     *可填可不填
     *
     * Generated from protobuf field <code>string mobile_phone = 2;</code>
     */
    private $mobile_phone = '';
    /**
     *用户民、昵称，必填
     *
     * Generated from protobuf field <code>string username = 3;</code>
     */
    private $username = '';
    /**
     *密码，必填
     *
     * Generated from protobuf field <code>string password = 4;</code>
     */
    private $password = '';
    /**
     *用户身份
     *
     * Generated from protobuf field <code>.cfwf.micro_service.account.USER_IDENTITY_TYPE identity = 5;</code>
     */
    private $identity = 0;
    /**
     *如果指定，则该userid在系统内不能存在
     *
     * Generated from protobuf field <code>fixed64 userid = 6;</code>
     */
    private $userid = 0;
    /**
     *可填可不填
     *
     * Generated from protobuf field <code>string email = 7;</code>
     */
    private $email = '';

    public function __construct() {
        \GPBMetadata\Account::initOnce();
        parent::__construct();
    }

    /**
     *可填可不填
     *
     * Generated from protobuf field <code>string cb_id = 1;</code>
     * @return string
     */
    public function getCbId()
    {
        return $this->cb_id;
    }

    /**
     *可填可不填
     *
     * Generated from protobuf field <code>string cb_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCbId($var)
    {
        GPBUtil::checkString($var, True);
        $this->cb_id = $var;

        return $this;
    }

    /**
     *可填可不填
     *
     * Generated from protobuf field <code>string mobile_phone = 2;</code>
     * @return string
     */
    public function getMobilePhone()
    {
        return $this->mobile_phone;
    }

    /**
     *可填可不填
     *
     * Generated from protobuf field <code>string mobile_phone = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMobilePhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile_phone = $var;

        return $this;
    }

    /**
     *用户民、昵称，必填
     *
     * Generated from protobuf field <code>string username = 3;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     *用户民、昵称，必填
     *
     * Generated from protobuf field <code>string username = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     *密码，必填
     *
     * Generated from protobuf field <code>string password = 4;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     *密码，必填
     *
     * Generated from protobuf field <code>string password = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     *用户身份
     *
     * Generated from protobuf field <code>.cfwf.micro_service.account.USER_IDENTITY_TYPE identity = 5;</code>
     * @return int
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     *用户身份
     *
     * Generated from protobuf field <code>.cfwf.micro_service.account.USER_IDENTITY_TYPE identity = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setIdentity($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\Account\USER_IDENTITY_TYPE::class);
        $this->identity = $var;

        return $this;
    }

    /**
     *如果指定，则该userid在系统内不能存在
     *
     * Generated from protobuf field <code>fixed64 userid = 6;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     *如果指定，则该userid在系统内不能存在
     *
     * Generated from protobuf field <code>fixed64 userid = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkUint64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     *可填可不填
     *
     * Generated from protobuf field <code>string email = 7;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     *可填可不填
     *
     * Generated from protobuf field <code>string email = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

}

