<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Cfwf\Micro_service\Account;

use Google\Protobuf\Internal\GPBUtil;

/**
 * SearchUserBaseInfo 搜索用户
 *
 * Generated from protobuf message <code>cfwf.micro_service.account.SearchUserBaseInfoRequest</code>
 */
class SearchUserBaseInfoRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *每页条数
     *
     * Generated from protobuf field <code>int32 page_size = 1;</code>
     */
    private $page_size = 0;
    /**
     *当前页。如果>总页数，则返回最后一页的数据
     *
     * Generated from protobuf field <code>int32 page = 2;</code>
     */
    private $page = 0;
    /**
     *昵称或 cb_id 关键字
     *
     * Generated from protobuf field <code>string keyword = 3;</code>
     */
    private $keyword = '';
    /**
     *按城市查找
     *
     * Generated from protobuf field <code>string cityid = 4;</code>
     */
    private $cityid = '';
    /**
     *性别，==""或者为 USER_SEX_INIT 时表示不限
     *
     * Generated from protobuf field <code>.cfwf.micro_service.account.USER_SEX sex = 5;</code>
     */
    private $sex = 0;
    /**
     *身份，==""表示不限
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.account.USER_IDENTITY_TYPE identity = 6;</code>
     */
    private $identity;

    public function __construct() {
        \GPBMetadata\Account::initOnce();
        parent::__construct();
    }

    /**
     *每页条数
     *
     * Generated from protobuf field <code>int32 page_size = 1;</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     *每页条数
     *
     * Generated from protobuf field <code>int32 page_size = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

    /**
     *当前页。如果>总页数，则返回最后一页的数据
     *
     * Generated from protobuf field <code>int32 page = 2;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     *当前页。如果>总页数，则返回最后一页的数据
     *
     * Generated from protobuf field <code>int32 page = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     *昵称或 cb_id 关键字
     *
     * Generated from protobuf field <code>string keyword = 3;</code>
     * @return string
     */
    public function getKeyword()
    {
        return $this->keyword;
    }

    /**
     *昵称或 cb_id 关键字
     *
     * Generated from protobuf field <code>string keyword = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyword($var)
    {
        GPBUtil::checkString($var, True);
        $this->keyword = $var;

        return $this;
    }

    /**
     *按城市查找
     *
     * Generated from protobuf field <code>string cityid = 4;</code>
     * @return string
     */
    public function getCityid()
    {
        return $this->cityid;
    }

    /**
     *按城市查找
     *
     * Generated from protobuf field <code>string cityid = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCityid($var)
    {
        GPBUtil::checkString($var, True);
        $this->cityid = $var;

        return $this;
    }

    /**
     *性别，==""或者为 USER_SEX_INIT 时表示不限
     *
     * Generated from protobuf field <code>.cfwf.micro_service.account.USER_SEX sex = 5;</code>
     * @return int
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     *性别，==""或者为 USER_SEX_INIT 时表示不限
     *
     * Generated from protobuf field <code>.cfwf.micro_service.account.USER_SEX sex = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\Account\USER_SEX::class);
        $this->sex = $var;

        return $this;
    }

    /**
     *身份，==""表示不限
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.account.USER_IDENTITY_TYPE identity = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     *身份，==""表示不限
     *
     * Generated from protobuf field <code>repeated .cfwf.micro_service.account.USER_IDENTITY_TYPE identity = 6;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIdentity($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Cfwf\Micro_service\Account\USER_IDENTITY_TYPE::class);
        $this->identity = $arr;

        return $this;
    }

}

