<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Cfwf\Micro_service\Account;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.account.SetUserInfoItemRequest</code>
 */
class SetUserInfoItemRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *客户端指令，第一个字段总是自己的id
     *
     * Generated from protobuf field <code>int64 userid = 1;</code>
     */
    private $userid = 0;
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.account.USER_INFO_TYPE info_type = 2;</code>
     */
    private $info_type = 0;
    /**
     * Generated from protobuf field <code>string value = 3;</code>
     */
    private $value = '';
    /**
     * Generated from protobuf field <code>int32 operatorid = 4;</code>
     */
    private $operatorid = 0;
    /**
     * Generated from protobuf field <code>int32 from_os = 5;</code>
     */
    private $from_os = 0;

    public function __construct() {
        \GPBMetadata\Account::initOnce();
        parent::__construct();
    }

    /**
     *客户端指令，第一个字段总是自己的id
     *
     * Generated from protobuf field <code>int64 userid = 1;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     *客户端指令，第一个字段总是自己的id
     *
     * Generated from protobuf field <code>int64 userid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkInt64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.account.USER_INFO_TYPE info_type = 2;</code>
     * @return int
     */
    public function getInfoType()
    {
        return $this->info_type;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.account.USER_INFO_TYPE info_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setInfoType($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\Account\USER_INFO_TYPE::class);
        $this->info_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string value = 3;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>string value = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 operatorid = 4;</code>
     * @return int
     */
    public function getOperatorid()
    {
        return $this->operatorid;
    }

    /**
     * Generated from protobuf field <code>int32 operatorid = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setOperatorid($var)
    {
        GPBUtil::checkInt32($var);
        $this->operatorid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 from_os = 5;</code>
     * @return int
     */
    public function getFromOs()
    {
        return $this->from_os;
    }

    /**
     * Generated from protobuf field <code>int32 from_os = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setFromOs($var)
    {
        GPBUtil::checkInt32($var);
        $this->from_os = $var;

        return $this;
    }

}

