<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Cfwf\Micro_service\Account;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.account.UserIdentity</code>
 */
class UserIdentity extends \Google\Protobuf\Internal\Message
{
    /**
     *是否中小学学生
     *
     * Generated from protobuf field <code>bool is_student = 1;</code>
     */
    private $is_student = false;
    /**
     *是否中小学教师
     *
     * Generated from protobuf field <code>bool is_teacher = 2;</code>
     */
    private $is_teacher = false;
    /**
     *是否中小学教务管理人员，校长
     *
     * Generated from protobuf field <code>bool is_school_manager = 3;</code>
     */
    private $is_school_manager = false;
    /**
     *是否中小学教研员
     *
     * Generated from protobuf field <code>bool is_teach_researcher = 4;</code>
     */
    private $is_teach_researcher = false;
    /**
     *是否中小学生家长
     *
     * Generated from protobuf field <code>bool is_student_parent = 5;</code>
     */
    private $is_student_parent = false;
    /**
     *是否 高职高校学生
     *
     * Generated from protobuf field <code>bool is_college_student = 6;</code>
     */
    private $is_college_student = false;
    /**
     *是否 高职高校教师
     *
     * Generated from protobuf field <code>bool is_college_teacher = 7;</code>
     */
    private $is_college_teacher = false;
    /**
     *是否 高职高校教务管理人员，校长
     *
     * Generated from protobuf field <code>bool is_college_manager = 8;</code>
     */
    private $is_college_manager = false;
    /**
     *是否 教育系统管理人员
     *
     * Generated from protobuf field <code>bool is_edu_management = 9;</code>
     */
    private $is_edu_management = false;
    /**
     *是否 商业机构用户
     *
     * Generated from protobuf field <code>bool is_commercial = 10;</code>
     */
    private $is_commercial = false;

    public function __construct() {
        \GPBMetadata\Account::initOnce();
        parent::__construct();
    }

    /**
     *是否中小学学生
     *
     * Generated from protobuf field <code>bool is_student = 1;</code>
     * @return bool
     */
    public function getIsStudent()
    {
        return $this->is_student;
    }

    /**
     *是否中小学学生
     *
     * Generated from protobuf field <code>bool is_student = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsStudent($var)
    {
        GPBUtil::checkBool($var);
        $this->is_student = $var;

        return $this;
    }

    /**
     *是否中小学教师
     *
     * Generated from protobuf field <code>bool is_teacher = 2;</code>
     * @return bool
     */
    public function getIsTeacher()
    {
        return $this->is_teacher;
    }

    /**
     *是否中小学教师
     *
     * Generated from protobuf field <code>bool is_teacher = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsTeacher($var)
    {
        GPBUtil::checkBool($var);
        $this->is_teacher = $var;

        return $this;
    }

    /**
     *是否中小学教务管理人员，校长
     *
     * Generated from protobuf field <code>bool is_school_manager = 3;</code>
     * @return bool
     */
    public function getIsSchoolManager()
    {
        return $this->is_school_manager;
    }

    /**
     *是否中小学教务管理人员，校长
     *
     * Generated from protobuf field <code>bool is_school_manager = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSchoolManager($var)
    {
        GPBUtil::checkBool($var);
        $this->is_school_manager = $var;

        return $this;
    }

    /**
     *是否中小学教研员
     *
     * Generated from protobuf field <code>bool is_teach_researcher = 4;</code>
     * @return bool
     */
    public function getIsTeachResearcher()
    {
        return $this->is_teach_researcher;
    }

    /**
     *是否中小学教研员
     *
     * Generated from protobuf field <code>bool is_teach_researcher = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsTeachResearcher($var)
    {
        GPBUtil::checkBool($var);
        $this->is_teach_researcher = $var;

        return $this;
    }

    /**
     *是否中小学生家长
     *
     * Generated from protobuf field <code>bool is_student_parent = 5;</code>
     * @return bool
     */
    public function getIsStudentParent()
    {
        return $this->is_student_parent;
    }

    /**
     *是否中小学生家长
     *
     * Generated from protobuf field <code>bool is_student_parent = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsStudentParent($var)
    {
        GPBUtil::checkBool($var);
        $this->is_student_parent = $var;

        return $this;
    }

    /**
     *是否 高职高校学生
     *
     * Generated from protobuf field <code>bool is_college_student = 6;</code>
     * @return bool
     */
    public function getIsCollegeStudent()
    {
        return $this->is_college_student;
    }

    /**
     *是否 高职高校学生
     *
     * Generated from protobuf field <code>bool is_college_student = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsCollegeStudent($var)
    {
        GPBUtil::checkBool($var);
        $this->is_college_student = $var;

        return $this;
    }

    /**
     *是否 高职高校教师
     *
     * Generated from protobuf field <code>bool is_college_teacher = 7;</code>
     * @return bool
     */
    public function getIsCollegeTeacher()
    {
        return $this->is_college_teacher;
    }

    /**
     *是否 高职高校教师
     *
     * Generated from protobuf field <code>bool is_college_teacher = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsCollegeTeacher($var)
    {
        GPBUtil::checkBool($var);
        $this->is_college_teacher = $var;

        return $this;
    }

    /**
     *是否 高职高校教务管理人员，校长
     *
     * Generated from protobuf field <code>bool is_college_manager = 8;</code>
     * @return bool
     */
    public function getIsCollegeManager()
    {
        return $this->is_college_manager;
    }

    /**
     *是否 高职高校教务管理人员，校长
     *
     * Generated from protobuf field <code>bool is_college_manager = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsCollegeManager($var)
    {
        GPBUtil::checkBool($var);
        $this->is_college_manager = $var;

        return $this;
    }

    /**
     *是否 教育系统管理人员
     *
     * Generated from protobuf field <code>bool is_edu_management = 9;</code>
     * @return bool
     */
    public function getIsEduManagement()
    {
        return $this->is_edu_management;
    }

    /**
     *是否 教育系统管理人员
     *
     * Generated from protobuf field <code>bool is_edu_management = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsEduManagement($var)
    {
        GPBUtil::checkBool($var);
        $this->is_edu_management = $var;

        return $this;
    }

    /**
     *是否 商业机构用户
     *
     * Generated from protobuf field <code>bool is_commercial = 10;</code>
     * @return bool
     */
    public function getIsCommercial()
    {
        return $this->is_commercial;
    }

    /**
     *是否 商业机构用户
     *
     * Generated from protobuf field <code>bool is_commercial = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsCommercial($var)
    {
        GPBUtil::checkBool($var);
        $this->is_commercial = $var;

        return $this;
    }

}

