<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Cfwf\Micro_service\Account;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.account.UserAndIdentity</code>
 */
class UserAndIdentity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 userid = 2;</code>
     */
    private $userid = 0;
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.account.UserIdentity identity = 3;</code>
     */
    private $identity = null;

    public function __construct() {
        \GPBMetadata\Account::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint64 userid = 2;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     * Generated from protobuf field <code>uint64 userid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkUint64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.account.UserIdentity identity = 3;</code>
     * @return \Cfwf\Micro_service\Account\UserIdentity
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.account.UserIdentity identity = 3;</code>
     * @param \Cfwf\Micro_service\Account\UserIdentity $var
     * @return $this
     */
    public function setIdentity($var)
    {
        GPBUtil::checkMessage($var, \Cfwf\Micro_service\Account\UserIdentity::class);
        $this->identity = $var;

        return $this;
    }

}

