<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Cfwf\Micro_service\Account;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户基本信息
 *
 * Generated from protobuf message <code>cfwf.micro_service.account.UserBaseInfo</code>
 */
class UserBaseInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed64 userid = 1;</code>
     */
    private $userid = 0;
    /**
     * Generated from protobuf field <code>string cb_id = 2;</code>
     */
    private $cb_id = '';
    /**
     *用户身份
     *
     * Generated from protobuf field <code>.cfwf.micro_service.account.UserIdentity identity = 3;</code>
     */
    private $identity = null;
    /**
     * Generated from protobuf field <code>string username = 4;</code>
     */
    private $username = '';
    /**
     * Generated from protobuf field <code>string user_face = 5;</code>
     */
    private $user_face = '';
    /**
     *为何有两个face? 在客户端列表好友时，若本地无好友自定义头像，则自定义头像延迟下载，先显示系统头像
     *
     * Generated from protobuf field <code>int32 default_face = 6;</code>
     */
    private $default_face = 0;
    /**
     * Generated from protobuf field <code>.cfwf.micro_service.account.USER_SEX sex = 7;</code>
     */
    private $sex = 0;
    /**
     * Generated from protobuf field <code>int32 cityid = 8;</code>
     */
    private $cityid = 0;
    /**
     * Generated from protobuf field <code>string mood = 9;</code>
     */
    private $mood = '';
    /**
     * Generated from protobuf field <code>int32 birthday = 10;</code>
     */
    private $birthday = 0;
    /**
     *绑定的手机号
     *
     * Generated from protobuf field <code>string bind_mobile = 11;</code>
     */
    private $bind_mobile = '';

    public function __construct() {
        \GPBMetadata\Account::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>fixed64 userid = 1;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     * Generated from protobuf field <code>fixed64 userid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkUint64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cb_id = 2;</code>
     * @return string
     */
    public function getCbId()
    {
        return $this->cb_id;
    }

    /**
     * Generated from protobuf field <code>string cb_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCbId($var)
    {
        GPBUtil::checkString($var, True);
        $this->cb_id = $var;

        return $this;
    }

    /**
     *用户身份
     *
     * Generated from protobuf field <code>.cfwf.micro_service.account.UserIdentity identity = 3;</code>
     * @return \Cfwf\Micro_service\Account\UserIdentity
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     *用户身份
     *
     * Generated from protobuf field <code>.cfwf.micro_service.account.UserIdentity identity = 3;</code>
     * @param \Cfwf\Micro_service\Account\UserIdentity $var
     * @return $this
     */
    public function setIdentity($var)
    {
        GPBUtil::checkMessage($var, \Cfwf\Micro_service\Account\UserIdentity::class);
        $this->identity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string username = 4;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_face = 5;</code>
     * @return string
     */
    public function getUserFace()
    {
        return $this->user_face;
    }

    /**
     * Generated from protobuf field <code>string user_face = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUserFace($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_face = $var;

        return $this;
    }

    /**
     *为何有两个face? 在客户端列表好友时，若本地无好友自定义头像，则自定义头像延迟下载，先显示系统头像
     *
     * Generated from protobuf field <code>int32 default_face = 6;</code>
     * @return int
     */
    public function getDefaultFace()
    {
        return $this->default_face;
    }

    /**
     *为何有两个face? 在客户端列表好友时，若本地无好友自定义头像，则自定义头像延迟下载，先显示系统头像
     *
     * Generated from protobuf field <code>int32 default_face = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setDefaultFace($var)
    {
        GPBUtil::checkInt32($var);
        $this->default_face = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.account.USER_SEX sex = 7;</code>
     * @return int
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     * Generated from protobuf field <code>.cfwf.micro_service.account.USER_SEX sex = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkEnum($var, \Cfwf\Micro_service\Account\USER_SEX::class);
        $this->sex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cityid = 8;</code>
     * @return int
     */
    public function getCityid()
    {
        return $this->cityid;
    }

    /**
     * Generated from protobuf field <code>int32 cityid = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setCityid($var)
    {
        GPBUtil::checkInt32($var);
        $this->cityid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mood = 9;</code>
     * @return string
     */
    public function getMood()
    {
        return $this->mood;
    }

    /**
     * Generated from protobuf field <code>string mood = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setMood($var)
    {
        GPBUtil::checkString($var, True);
        $this->mood = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 birthday = 10;</code>
     * @return int
     */
    public function getBirthday()
    {
        return $this->birthday;
    }

    /**
     * Generated from protobuf field <code>int32 birthday = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setBirthday($var)
    {
        GPBUtil::checkInt32($var);
        $this->birthday = $var;

        return $this;
    }

    /**
     *绑定的手机号
     *
     * Generated from protobuf field <code>string bind_mobile = 11;</code>
     * @return string
     */
    public function getBindMobile()
    {
        return $this->bind_mobile;
    }

    /**
     *绑定的手机号
     *
     * Generated from protobuf field <code>string bind_mobile = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setBindMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->bind_mobile = $var;

        return $this;
    }

}

