<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Cfwf\Micro_service\Account;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户简单信息
 *
 * Generated from protobuf message <code>cfwf.micro_service.account.UserSimpleInfo</code>
 */
class UserSimpleInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed64 userid = 1;</code>
     */
    private $userid = 0;
    /**
     * Generated from protobuf field <code>string username = 2;</code>
     */
    private $username = '';
    /**
     *用户自定义头像，如果该项没有值，则使用系统头像。 本接口数据一般用于网页上列表显示用户信息，无客户端延迟下载缓存头像需求
     *
     * Generated from protobuf field <code>string user_face = 3;</code>
     */
    private $user_face = '';
    /**
     *系统头像
     *
     * Generated from protobuf field <code>int32 default_face = 4;</code>
     */
    private $default_face = 0;

    public function __construct() {
        \GPBMetadata\Account::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>fixed64 userid = 1;</code>
     * @return int|string
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     * Generated from protobuf field <code>fixed64 userid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkUint64($var);
        $this->userid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     *用户自定义头像，如果该项没有值，则使用系统头像。 本接口数据一般用于网页上列表显示用户信息，无客户端延迟下载缓存头像需求
     *
     * Generated from protobuf field <code>string user_face = 3;</code>
     * @return string
     */
    public function getUserFace()
    {
        return $this->user_face;
    }

    /**
     *用户自定义头像，如果该项没有值，则使用系统头像。 本接口数据一般用于网页上列表显示用户信息，无客户端延迟下载缓存头像需求
     *
     * Generated from protobuf field <code>string user_face = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUserFace($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_face = $var;

        return $this;
    }

    /**
     *系统头像
     *
     * Generated from protobuf field <code>int32 default_face = 4;</code>
     * @return int
     */
    public function getDefaultFace()
    {
        return $this->default_face;
    }

    /**
     *系统头像
     *
     * Generated from protobuf field <code>int32 default_face = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setDefaultFace($var)
    {
        GPBUtil::checkInt32($var);
        $this->default_face = $var;

        return $this;
    }

}

