<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_subjects.proto

namespace Cfwf\Micro_service\School_subject;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cfwf.micro_service.school_subject.GetTextbookVersionRequest</code>
 */
class GetTextbookVersionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *所在地区
     *
     * Generated from protobuf field <code>int32 cityid = 1;</code>
     */
    private $cityid = 0;
    /**
     *年级
     *
     * Generated from protobuf field <code>int32 grade = 2;</code>
     */
    private $grade = 0;
    /**
     *科目
     *
     * Generated from protobuf field <code>int32 subject = 3;</code>
     */
    private $subject = 0;
    /**
     *年份： 2018
     *
     * Generated from protobuf field <code>int32 year = 4;</code>
     */
    private $year = 0;
    /**
     *学期：1=上 2=下 3=全年  和 教材 volume 统一
     *
     * Generated from protobuf field <code>int32 term = 5;</code>
     */
    private $term = 0;

    public function __construct() {
        \GPBMetadata\SchoolSubjects::initOnce();
        parent::__construct();
    }

    /**
     *所在地区
     *
     * Generated from protobuf field <code>int32 cityid = 1;</code>
     * @return int
     */
    public function getCityid()
    {
        return $this->cityid;
    }

    /**
     *所在地区
     *
     * Generated from protobuf field <code>int32 cityid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCityid($var)
    {
        GPBUtil::checkInt32($var);
        $this->cityid = $var;

        return $this;
    }

    /**
     *年级
     *
     * Generated from protobuf field <code>int32 grade = 2;</code>
     * @return int
     */
    public function getGrade()
    {
        return $this->grade;
    }

    /**
     *年级
     *
     * Generated from protobuf field <code>int32 grade = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setGrade($var)
    {
        GPBUtil::checkInt32($var);
        $this->grade = $var;

        return $this;
    }

    /**
     *科目
     *
     * Generated from protobuf field <code>int32 subject = 3;</code>
     * @return int
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     *科目
     *
     * Generated from protobuf field <code>int32 subject = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkInt32($var);
        $this->subject = $var;

        return $this;
    }

    /**
     *年份： 2018
     *
     * Generated from protobuf field <code>int32 year = 4;</code>
     * @return int
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     *年份： 2018
     *
     * Generated from protobuf field <code>int32 year = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setYear($var)
    {
        GPBUtil::checkInt32($var);
        $this->year = $var;

        return $this;
    }

    /**
     *学期：1=上 2=下 3=全年  和 教材 volume 统一
     *
     * Generated from protobuf field <code>int32 term = 5;</code>
     * @return int
     */
    public function getTerm()
    {
        return $this->term;
    }

    /**
     *学期：1=上 2=下 3=全年  和 教材 volume 统一
     *
     * Generated from protobuf field <code>int32 term = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setTerm($var)
    {
        GPBUtil::checkInt32($var);
        $this->term = $var;

        return $this;
    }

}

